// This file is automatically generated. Do not modify.

package gentest

import (
	"fmt"
)

var _ = fmt.Sprintf

type NestedColor struct {
	Rgb *Rgb `thrift:"1,required,implicit" json:"rgb"`
}

type Rgb struct {
	Red   *int32 `thrift:"1,required,implicit" json:"red"`
	Green *int32 `thrift:"2,required,implicit" json:"green"`
	Blue  *int32 `thrift:"3,required,implicit" json:"blue"`
}
