// This file is automatically generated. Do not modify.

package gentest

import (
	"fmt"
)

var _ = fmt.Sprintf

type Binary []byte

func (e Binary) Ptr() *Binary { return &e }

type Int32 int32

func (e Int32) Ptr() *Int32 { return &e }

type String string

func (e String) Ptr() *String { return &e }

type St struct {
	B *Binary `thrift:"1,required" json:"b"`
	S *String `thrift:"2,required" json:"s"`
	I *Int32  `thrift:"3,required" json:"i"`
}
