// DO NOT EDIT. Code generated by pigeon, run "go generate" to update.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

type namespace struct {
	scope     string
	namespace string
}

type typeDef struct {
	name string
	typ  *Type
}

type exception *Struct

type include string

func toIfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

func ifaceSliceToString(v interface{}) string {
	ifs := toIfaceSlice(v)
	b := make([]byte, len(ifs))
	for i, v := range ifs {
		b[i] = v.([]uint8)[0]
	}
	return string(b)
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Grammar",
			pos:  position{line: 43, col: 1, offset: 586},
			expr: &actionExpr{
				pos: position{line: 43, col: 11, offset: 598},
				run: (*parser).callonGrammar1,
				expr: &seqExpr{
					pos: position{line: 43, col: 11, offset: 598},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 43, col: 11, offset: 598},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 43, col: 14, offset: 601},
							label: "statements",
							expr: &zeroOrMoreExpr{
								pos: position{line: 43, col: 25, offset: 612},
								expr: &seqExpr{
									pos: position{line: 43, col: 27, offset: 614},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 43, col: 27, offset: 614},
											name: "Statement",
										},
										&ruleRefExpr{
											pos:  position{line: 43, col: 37, offset: 624},
											name: "__",
										},
									},
								},
							},
						},
						&choiceExpr{
							pos: position{line: 43, col: 44, offset: 631},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 43, col: 44, offset: 631},
									name: "EOF",
								},
								&ruleRefExpr{
									pos:  position{line: 43, col: 50, offset: 637},
									name: "SyntaxError",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SyntaxError",
			pos:  position{line: 84, col: 1, offset: 1698},
			expr: &actionExpr{
				pos: position{line: 84, col: 15, offset: 1714},
				run: (*parser).callonSyntaxError1,
				expr: &anyMatcher{
					line: 84, col: 15, offset: 1714,
				},
			},
		},
		{
			name: "Include",
			pos:  position{line: 88, col: 1, offset: 1769},
			expr: &actionExpr{
				pos: position{line: 88, col: 11, offset: 1781},
				run: (*parser).callonInclude1,
				expr: &seqExpr{
					pos: position{line: 88, col: 11, offset: 1781},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 88, col: 11, offset: 1781},
							val:        "include",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 88, col: 21, offset: 1791},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 88, col: 23, offset: 1793},
							label: "file",
							expr: &ruleRefExpr{
								pos:  position{line: 88, col: 28, offset: 1798},
								name: "Literal",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 88, col: 36, offset: 1806},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Statement",
			pos:  position{line: 92, col: 1, offset: 1851},
			expr: &choiceExpr{
				pos: position{line: 92, col: 13, offset: 1865},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 92, col: 13, offset: 1865},
						name: "Include",
					},
					&ruleRefExpr{
						pos:  position{line: 92, col: 23, offset: 1875},
						name: "Namespace",
					},
					&ruleRefExpr{
						pos:  position{line: 92, col: 35, offset: 1887},
						name: "Const",
					},
					&ruleRefExpr{
						pos:  position{line: 92, col: 43, offset: 1895},
						name: "Enum",
					},
					&ruleRefExpr{
						pos:  position{line: 92, col: 50, offset: 1902},
						name: "TypeDef",
					},
					&ruleRefExpr{
						pos:  position{line: 92, col: 60, offset: 1912},
						name: "Struct",
					},
					&ruleRefExpr{
						pos:  position{line: 92, col: 69, offset: 1921},
						name: "Exception",
					},
					&ruleRefExpr{
						pos:  position{line: 92, col: 81, offset: 1933},
						name: "Service",
					},
				},
			},
		},
		{
			name: "Namespace",
			pos:  position{line: 94, col: 1, offset: 1942},
			expr: &actionExpr{
				pos: position{line: 94, col: 13, offset: 1956},
				run: (*parser).callonNamespace1,
				expr: &seqExpr{
					pos: position{line: 94, col: 13, offset: 1956},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 94, col: 13, offset: 1956},
							val:        "namespace",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 94, col: 25, offset: 1968},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 94, col: 27, offset: 1970},
							label: "scope",
							expr: &oneOrMoreExpr{
								pos: position{line: 94, col: 33, offset: 1976},
								expr: &charClassMatcher{
									pos:        position{line: 94, col: 33, offset: 1976},
									val:        "[a-z.-]",
									chars:      []rune{'.', '-'},
									ranges:     []rune{'a', 'z'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 94, col: 42, offset: 1985},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 94, col: 44, offset: 1987},
							label: "ns",
							expr: &ruleRefExpr{
								pos:  position{line: 94, col: 47, offset: 1990},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 94, col: 58, offset: 2001},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Const",
			pos:  position{line: 101, col: 1, offset: 2112},
			expr: &actionExpr{
				pos: position{line: 101, col: 9, offset: 2122},
				run: (*parser).callonConst1,
				expr: &seqExpr{
					pos: position{line: 101, col: 9, offset: 2122},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 101, col: 9, offset: 2122},
							val:        "const",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 101, col: 17, offset: 2130},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 101, col: 19, offset: 2132},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 101, col: 23, offset: 2136},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 101, col: 33, offset: 2146},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 101, col: 35, offset: 2148},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 101, col: 40, offset: 2153},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 101, col: 51, offset: 2164},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 101, col: 53, offset: 2166},
							val:        "=",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 101, col: 57, offset: 2170},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 101, col: 59, offset: 2172},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 101, col: 65, offset: 2178},
								name: "ConstValue",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 101, col: 76, offset: 2189},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Enum",
			pos:  position{line: 109, col: 1, offset: 2297},
			expr: &actionExpr{
				pos: position{line: 109, col: 8, offset: 2306},
				run: (*parser).callonEnum1,
				expr: &seqExpr{
					pos: position{line: 109, col: 8, offset: 2306},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 109, col: 8, offset: 2306},
							val:        "enum",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 109, col: 15, offset: 2313},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 109, col: 17, offset: 2315},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 109, col: 22, offset: 2320},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 109, col: 33, offset: 2331},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 109, col: 35, offset: 2333},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 109, col: 39, offset: 2337},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 109, col: 42, offset: 2340},
							label: "values",
							expr: &zeroOrMoreExpr{
								pos: position{line: 109, col: 49, offset: 2347},
								expr: &seqExpr{
									pos: position{line: 109, col: 50, offset: 2348},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 109, col: 50, offset: 2348},
											name: "EnumValue",
										},
										&ruleRefExpr{
											pos:  position{line: 109, col: 60, offset: 2358},
											name: "__",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 109, col: 65, offset: 2363},
							val:        "}",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 109, col: 69, offset: 2367},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "EnumValue",
			pos:  position{line: 132, col: 1, offset: 2883},
			expr: &actionExpr{
				pos: position{line: 132, col: 13, offset: 2897},
				run: (*parser).callonEnumValue1,
				expr: &seqExpr{
					pos: position{line: 132, col: 13, offset: 2897},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 132, col: 13, offset: 2897},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 18, offset: 2902},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 132, col: 29, offset: 2913},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 132, col: 31, offset: 2915},
							label: "value",
							expr: &zeroOrOneExpr{
								pos: position{line: 132, col: 37, offset: 2921},
								expr: &seqExpr{
									pos: position{line: 132, col: 38, offset: 2922},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 132, col: 38, offset: 2922},
											val:        "=",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 132, col: 42, offset: 2926},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 132, col: 44, offset: 2928},
											name: "IntConstant",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 132, col: 58, offset: 2942},
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 58, offset: 2942},
								name: "ListSeparator",
							},
						},
					},
				},
			},
		},
		{
			name: "TypeDef",
			pos:  position{line: 143, col: 1, offset: 3121},
			expr: &actionExpr{
				pos: position{line: 143, col: 11, offset: 3133},
				run: (*parser).callonTypeDef1,
				expr: &seqExpr{
					pos: position{line: 143, col: 11, offset: 3133},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 143, col: 11, offset: 3133},
							val:        "typedef",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 21, offset: 3143},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 143, col: 23, offset: 3145},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 143, col: 27, offset: 3149},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 37, offset: 3159},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 143, col: 39, offset: 3161},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 143, col: 44, offset: 3166},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 55, offset: 3177},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Struct",
			pos:  position{line: 150, col: 1, offset: 3267},
			expr: &actionExpr{
				pos: position{line: 150, col: 10, offset: 3278},
				run: (*parser).callonStruct1,
				expr: &seqExpr{
					pos: position{line: 150, col: 10, offset: 3278},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 150, col: 10, offset: 3278},
							val:        "struct",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 150, col: 19, offset: 3287},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 150, col: 21, offset: 3289},
							label: "st",
							expr: &ruleRefExpr{
								pos:  position{line: 150, col: 24, offset: 3292},
								name: "StructLike",
							},
						},
					},
				},
			},
		},
		{
			name: "Exception",
			pos:  position{line: 151, col: 1, offset: 3332},
			expr: &actionExpr{
				pos: position{line: 151, col: 13, offset: 3346},
				run: (*parser).callonException1,
				expr: &seqExpr{
					pos: position{line: 151, col: 13, offset: 3346},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 151, col: 13, offset: 3346},
							val:        "exception",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 151, col: 25, offset: 3358},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 151, col: 27, offset: 3360},
							label: "st",
							expr: &ruleRefExpr{
								pos:  position{line: 151, col: 30, offset: 3363},
								name: "StructLike",
							},
						},
					},
				},
			},
		},
		{
			name: "StructLike",
			pos:  position{line: 152, col: 1, offset: 3414},
			expr: &actionExpr{
				pos: position{line: 152, col: 14, offset: 3429},
				run: (*parser).callonStructLike1,
				expr: &seqExpr{
					pos: position{line: 152, col: 14, offset: 3429},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 152, col: 14, offset: 3429},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 152, col: 19, offset: 3434},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 152, col: 30, offset: 3445},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 152, col: 33, offset: 3448},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 152, col: 37, offset: 3452},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 152, col: 40, offset: 3455},
							label: "fields",
							expr: &ruleRefExpr{
								pos:  position{line: 152, col: 47, offset: 3462},
								name: "FieldList",
							},
						},
						&litMatcher{
							pos:        position{line: 152, col: 57, offset: 3472},
							val:        "}",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 152, col: 61, offset: 3476},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "FieldList",
			pos:  position{line: 162, col: 1, offset: 3610},
			expr: &actionExpr{
				pos: position{line: 162, col: 13, offset: 3624},
				run: (*parser).callonFieldList1,
				expr: &labeledExpr{
					pos:   position{line: 162, col: 13, offset: 3624},
					label: "fields",
					expr: &zeroOrMoreExpr{
						pos: position{line: 162, col: 20, offset: 3631},
						expr: &seqExpr{
							pos: position{line: 162, col: 21, offset: 3632},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 162, col: 21, offset: 3632},
									name: "Field",
								},
								&ruleRefExpr{
									pos:  position{line: 162, col: 27, offset: 3638},
									name: "__",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Field",
			pos:  position{line: 171, col: 1, offset: 3798},
			expr: &actionExpr{
				pos: position{line: 171, col: 9, offset: 3808},
				run: (*parser).callonField1,
				expr: &seqExpr{
					pos: position{line: 171, col: 9, offset: 3808},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 171, col: 9, offset: 3808},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 171, col: 12, offset: 3811},
								name: "IntConstant",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 24, offset: 3823},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 171, col: 26, offset: 3825},
							val:        ":",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 30, offset: 3829},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 171, col: 32, offset: 3831},
							label: "req",
							expr: &zeroOrOneExpr{
								pos: position{line: 171, col: 36, offset: 3835},
								expr: &ruleRefExpr{
									pos:  position{line: 171, col: 36, offset: 3835},
									name: "FieldReq",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 46, offset: 3845},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 171, col: 48, offset: 3847},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 171, col: 52, offset: 3851},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 62, offset: 3861},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 171, col: 64, offset: 3863},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 171, col: 69, offset: 3868},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 80, offset: 3879},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 171, col: 82, offset: 3881},
							label: "def",
							expr: &zeroOrOneExpr{
								pos: position{line: 171, col: 86, offset: 3885},
								expr: &seqExpr{
									pos: position{line: 171, col: 87, offset: 3886},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 171, col: 87, offset: 3886},
											val:        "=",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 171, col: 91, offset: 3890},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 171, col: 93, offset: 3892},
											name: "ConstValue",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 171, col: 106, offset: 3905},
							expr: &ruleRefExpr{
								pos:  position{line: 171, col: 106, offset: 3905},
								name: "ListSeparator",
							},
						},
					},
				},
			},
		},
		{
			name: "FieldReq",
			pos:  position{line: 186, col: 1, offset: 4165},
			expr: &actionExpr{
				pos: position{line: 186, col: 12, offset: 4178},
				run: (*parser).callonFieldReq1,
				expr: &choiceExpr{
					pos: position{line: 186, col: 13, offset: 4179},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 186, col: 13, offset: 4179},
							val:        "required",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 186, col: 26, offset: 4192},
							val:        "optional",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Service",
			pos:  position{line: 190, col: 1, offset: 4263},
			expr: &actionExpr{
				pos: position{line: 190, col: 11, offset: 4275},
				run: (*parser).callonService1,
				expr: &seqExpr{
					pos: position{line: 190, col: 11, offset: 4275},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 190, col: 11, offset: 4275},
							val:        "service",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 190, col: 21, offset: 4285},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 190, col: 23, offset: 4287},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 190, col: 28, offset: 4292},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 190, col: 39, offset: 4303},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 190, col: 41, offset: 4305},
							label: "extends",
							expr: &zeroOrOneExpr{
								pos: position{line: 190, col: 49, offset: 4313},
								expr: &seqExpr{
									pos: position{line: 190, col: 50, offset: 4314},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 190, col: 50, offset: 4314},
											val:        "extends",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 190, col: 60, offset: 4324},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 190, col: 63, offset: 4327},
											name: "Identifier",
										},
										&ruleRefExpr{
											pos:  position{line: 190, col: 74, offset: 4338},
											name: "__",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 190, col: 79, offset: 4343},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 190, col: 82, offset: 4346},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 190, col: 86, offset: 4350},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 190, col: 89, offset: 4353},
							label: "methods",
							expr: &zeroOrMoreExpr{
								pos: position{line: 190, col: 97, offset: 4361},
								expr: &seqExpr{
									pos: position{line: 190, col: 98, offset: 4362},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 190, col: 98, offset: 4362},
											name: "Function",
										},
										&ruleRefExpr{
											pos:  position{line: 190, col: 107, offset: 4371},
											name: "__",
										},
									},
								},
							},
						},
						&choiceExpr{
							pos: position{line: 190, col: 113, offset: 4377},
							alternatives: []interface{}{
								&litMatcher{
									pos:        position{line: 190, col: 113, offset: 4377},
									val:        "}",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 190, col: 119, offset: 4383},
									name: "EndOfServiceError",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 190, col: 138, offset: 4402},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "EndOfServiceError",
			pos:  position{line: 205, col: 1, offset: 4743},
			expr: &actionExpr{
				pos: position{line: 205, col: 21, offset: 4765},
				run: (*parser).callonEndOfServiceError1,
				expr: &anyMatcher{
					line: 205, col: 21, offset: 4765,
				},
			},
		},
		{
			name: "Function",
			pos:  position{line: 209, col: 1, offset: 4831},
			expr: &actionExpr{
				pos: position{line: 209, col: 12, offset: 4844},
				run: (*parser).callonFunction1,
				expr: &seqExpr{
					pos: position{line: 209, col: 12, offset: 4844},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 209, col: 12, offset: 4844},
							label: "oneway",
							expr: &zeroOrOneExpr{
								pos: position{line: 209, col: 19, offset: 4851},
								expr: &seqExpr{
									pos: position{line: 209, col: 20, offset: 4852},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 209, col: 20, offset: 4852},
											val:        "oneway",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 209, col: 29, offset: 4861},
											name: "__",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 209, col: 34, offset: 4866},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 209, col: 38, offset: 4870},
								name: "FunctionType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 209, col: 51, offset: 4883},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 209, col: 54, offset: 4886},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 209, col: 59, offset: 4891},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 209, col: 70, offset: 4902},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 209, col: 72, offset: 4904},
							val:        "(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 209, col: 76, offset: 4908},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 209, col: 79, offset: 4911},
							label: "arguments",
							expr: &ruleRefExpr{
								pos:  position{line: 209, col: 89, offset: 4921},
								name: "FieldList",
							},
						},
						&litMatcher{
							pos:        position{line: 209, col: 99, offset: 4931},
							val:        ")",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 209, col: 103, offset: 4935},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 209, col: 106, offset: 4938},
							label: "exceptions",
							expr: &zeroOrOneExpr{
								pos: position{line: 209, col: 117, offset: 4949},
								expr: &ruleRefExpr{
									pos:  position{line: 209, col: 117, offset: 4949},
									name: "Throws",
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 209, col: 125, offset: 4957},
							expr: &ruleRefExpr{
								pos:  position{line: 209, col: 125, offset: 4957},
								name: "ListSeparator",
							},
						},
					},
				},
			},
		},
		{
			name: "FunctionType",
			pos:  position{line: 232, col: 1, offset: 5338},
			expr: &actionExpr{
				pos: position{line: 232, col: 16, offset: 5355},
				run: (*parser).callonFunctionType1,
				expr: &labeledExpr{
					pos:   position{line: 232, col: 16, offset: 5355},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 232, col: 21, offset: 5360},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 232, col: 21, offset: 5360},
								val:        "void",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 232, col: 30, offset: 5369},
								name: "FieldType",
							},
						},
					},
				},
			},
		},
		{
			name: "Throws",
			pos:  position{line: 239, col: 1, offset: 5476},
			expr: &actionExpr{
				pos: position{line: 239, col: 10, offset: 5487},
				run: (*parser).callonThrows1,
				expr: &seqExpr{
					pos: position{line: 239, col: 10, offset: 5487},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 239, col: 10, offset: 5487},
							val:        "throws",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 239, col: 19, offset: 5496},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 239, col: 22, offset: 5499},
							val:        "(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 239, col: 26, offset: 5503},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 239, col: 29, offset: 5506},
							label: "exceptions",
							expr: &ruleRefExpr{
								pos:  position{line: 239, col: 40, offset: 5517},
								name: "FieldList",
							},
						},
						&litMatcher{
							pos:        position{line: 239, col: 50, offset: 5527},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "FieldType",
			pos:  position{line: 243, col: 1, offset: 5560},
			expr: &actionExpr{
				pos: position{line: 243, col: 13, offset: 5574},
				run: (*parser).callonFieldType1,
				expr: &labeledExpr{
					pos:   position{line: 243, col: 13, offset: 5574},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 243, col: 18, offset: 5579},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 243, col: 18, offset: 5579},
								name: "BaseType",
							},
							&ruleRefExpr{
								pos:  position{line: 243, col: 29, offset: 5590},
								name: "ContainerType",
							},
							&ruleRefExpr{
								pos:  position{line: 243, col: 45, offset: 5606},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "DefinitionType",
			pos:  position{line: 250, col: 1, offset: 5716},
			expr: &actionExpr{
				pos: position{line: 250, col: 18, offset: 5735},
				run: (*parser).callonDefinitionType1,
				expr: &labeledExpr{
					pos:   position{line: 250, col: 18, offset: 5735},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 250, col: 23, offset: 5740},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 250, col: 23, offset: 5740},
								name: "BaseType",
							},
							&ruleRefExpr{
								pos:  position{line: 250, col: 34, offset: 5751},
								name: "ContainerType",
							},
						},
					},
				},
			},
		},
		{
			name: "BaseType",
			pos:  position{line: 254, col: 1, offset: 5788},
			expr: &actionExpr{
				pos: position{line: 254, col: 12, offset: 5801},
				run: (*parser).callonBaseType1,
				expr: &choiceExpr{
					pos: position{line: 254, col: 13, offset: 5802},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 254, col: 13, offset: 5802},
							val:        "bool",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 254, col: 22, offset: 5811},
							val:        "byte",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 254, col: 31, offset: 5820},
							val:        "i16",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 254, col: 39, offset: 5828},
							val:        "i32",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 254, col: 47, offset: 5836},
							val:        "i64",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 254, col: 55, offset: 5844},
							val:        "double",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 254, col: 66, offset: 5855},
							val:        "string",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 254, col: 77, offset: 5866},
							val:        "binary",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "ContainerType",
			pos:  position{line: 258, col: 1, offset: 5923},
			expr: &actionExpr{
				pos: position{line: 258, col: 17, offset: 5941},
				run: (*parser).callonContainerType1,
				expr: &labeledExpr{
					pos:   position{line: 258, col: 17, offset: 5941},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 258, col: 22, offset: 5946},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 258, col: 22, offset: 5946},
								name: "MapType",
							},
							&ruleRefExpr{
								pos:  position{line: 258, col: 32, offset: 5956},
								name: "SetType",
							},
							&ruleRefExpr{
								pos:  position{line: 258, col: 42, offset: 5966},
								name: "ListType",
							},
						},
					},
				},
			},
		},
		{
			name: "MapType",
			pos:  position{line: 262, col: 1, offset: 5998},
			expr: &actionExpr{
				pos: position{line: 262, col: 11, offset: 6010},
				run: (*parser).callonMapType1,
				expr: &seqExpr{
					pos: position{line: 262, col: 11, offset: 6010},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 262, col: 11, offset: 6010},
							expr: &ruleRefExpr{
								pos:  position{line: 262, col: 11, offset: 6010},
								name: "CppType",
							},
						},
						&litMatcher{
							pos:        position{line: 262, col: 20, offset: 6019},
							val:        "map<",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 262, col: 27, offset: 6026},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 262, col: 30, offset: 6029},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 262, col: 34, offset: 6033},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 262, col: 44, offset: 6043},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 262, col: 47, offset: 6046},
							val:        ",",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 262, col: 51, offset: 6050},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 262, col: 54, offset: 6053},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 262, col: 60, offset: 6059},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 262, col: 70, offset: 6069},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 262, col: 73, offset: 6072},
							val:        ">",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "SetType",
			pos:  position{line: 270, col: 1, offset: 6171},
			expr: &actionExpr{
				pos: position{line: 270, col: 11, offset: 6183},
				run: (*parser).callonSetType1,
				expr: &seqExpr{
					pos: position{line: 270, col: 11, offset: 6183},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 270, col: 11, offset: 6183},
							expr: &ruleRefExpr{
								pos:  position{line: 270, col: 11, offset: 6183},
								name: "CppType",
							},
						},
						&litMatcher{
							pos:        position{line: 270, col: 20, offset: 6192},
							val:        "set<",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 270, col: 27, offset: 6199},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 270, col: 30, offset: 6202},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 270, col: 34, offset: 6206},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 270, col: 44, offset: 6216},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 270, col: 47, offset: 6219},
							val:        ">",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "ListType",
			pos:  position{line: 277, col: 1, offset: 6292},
			expr: &actionExpr{
				pos: position{line: 277, col: 12, offset: 6305},
				run: (*parser).callonListType1,
				expr: &seqExpr{
					pos: position{line: 277, col: 12, offset: 6305},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 277, col: 12, offset: 6305},
							val:        "list<",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 277, col: 20, offset: 6313},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 277, col: 23, offset: 6316},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 277, col: 27, offset: 6320},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 277, col: 37, offset: 6330},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 277, col: 40, offset: 6333},
							val:        ">",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "CppType",
			pos:  position{line: 284, col: 1, offset: 6407},
			expr: &actionExpr{
				pos: position{line: 284, col: 11, offset: 6419},
				run: (*parser).callonCppType1,
				expr: &seqExpr{
					pos: position{line: 284, col: 11, offset: 6419},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 284, col: 11, offset: 6419},
							val:        "cpp_type",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 284, col: 22, offset: 6430},
							label: "cppType",
							expr: &ruleRefExpr{
								pos:  position{line: 284, col: 30, offset: 6438},
								name: "Literal",
							},
						},
					},
				},
			},
		},
		{
			name: "ConstValue",
			pos:  position{line: 288, col: 1, offset: 6472},
			expr: &choiceExpr{
				pos: position{line: 288, col: 14, offset: 6487},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 288, col: 14, offset: 6487},
						name: "Literal",
					},
					&ruleRefExpr{
						pos:  position{line: 288, col: 24, offset: 6497},
						name: "DoubleConstant",
					},
					&ruleRefExpr{
						pos:  position{line: 288, col: 41, offset: 6514},
						name: "IntConstant",
					},
					&ruleRefExpr{
						pos:  position{line: 288, col: 55, offset: 6528},
						name: "ConstMap",
					},
					&ruleRefExpr{
						pos:  position{line: 288, col: 66, offset: 6539},
						name: "ConstList",
					},
					&ruleRefExpr{
						pos:  position{line: 288, col: 78, offset: 6551},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "IntConstant",
			pos:  position{line: 290, col: 1, offset: 6563},
			expr: &actionExpr{
				pos: position{line: 290, col: 15, offset: 6579},
				run: (*parser).callonIntConstant1,
				expr: &seqExpr{
					pos: position{line: 290, col: 15, offset: 6579},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 290, col: 15, offset: 6579},
							expr: &charClassMatcher{
								pos:        position{line: 290, col: 15, offset: 6579},
								val:        "[-+]",
								chars:      []rune{'-', '+'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 290, col: 21, offset: 6585},
							expr: &ruleRefExpr{
								pos:  position{line: 290, col: 21, offset: 6585},
								name: "Digit",
							},
						},
					},
				},
			},
		},
		{
			name: "DoubleConstant",
			pos:  position{line: 294, col: 1, offset: 6646},
			expr: &actionExpr{
				pos: position{line: 294, col: 18, offset: 6665},
				run: (*parser).callonDoubleConstant1,
				expr: &seqExpr{
					pos: position{line: 294, col: 18, offset: 6665},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 294, col: 18, offset: 6665},
							expr: &charClassMatcher{
								pos:        position{line: 294, col: 18, offset: 6665},
								val:        "[+-]",
								chars:      []rune{'+', '-'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 294, col: 24, offset: 6671},
							expr: &ruleRefExpr{
								pos:  position{line: 294, col: 24, offset: 6671},
								name: "Digit",
							},
						},
						&litMatcher{
							pos:        position{line: 294, col: 31, offset: 6678},
							val:        ".",
							ignoreCase: false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 294, col: 35, offset: 6682},
							expr: &ruleRefExpr{
								pos:  position{line: 294, col: 35, offset: 6682},
								name: "Digit",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 294, col: 42, offset: 6689},
							expr: &seqExpr{
								pos: position{line: 294, col: 44, offset: 6691},
								exprs: []interface{}{
									&charClassMatcher{
										pos:        position{line: 294, col: 44, offset: 6691},
										val:        "['Ee']",
										chars:      []rune{'\'', 'E', 'e', '\''},
										ignoreCase: false,
										inverted:   false,
									},
									&ruleRefExpr{
										pos:  position{line: 294, col: 51, offset: 6698},
										name: "IntConstant",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ConstList",
			pos:  position{line: 298, col: 1, offset: 6765},
			expr: &actionExpr{
				pos: position{line: 298, col: 13, offset: 6779},
				run: (*parser).callonConstList1,
				expr: &seqExpr{
					pos: position{line: 298, col: 13, offset: 6779},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 298, col: 13, offset: 6779},
							val:        "[",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 298, col: 17, offset: 6783},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 298, col: 20, offset: 6786},
							label: "values",
							expr: &zeroOrMoreExpr{
								pos: position{line: 298, col: 27, offset: 6793},
								expr: &seqExpr{
									pos: position{line: 298, col: 28, offset: 6794},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 298, col: 28, offset: 6794},
											name: "ConstValue",
										},
										&ruleRefExpr{
											pos:  position{line: 298, col: 39, offset: 6805},
											name: "__",
										},
										&zeroOrOneExpr{
											pos: position{line: 298, col: 42, offset: 6808},
											expr: &ruleRefExpr{
												pos:  position{line: 298, col: 42, offset: 6808},
												name: "ListSeparator",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 298, col: 57, offset: 6823},
											name: "__",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 298, col: 62, offset: 6828},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 298, col: 65, offset: 6831},
							val:        "]",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "ConstMap",
			pos:  position{line: 307, col: 1, offset: 7004},
			expr: &actionExpr{
				pos: position{line: 307, col: 12, offset: 7017},
				run: (*parser).callonConstMap1,
				expr: &seqExpr{
					pos: position{line: 307, col: 12, offset: 7017},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 307, col: 12, offset: 7017},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 307, col: 16, offset: 7021},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 307, col: 19, offset: 7024},
							label: "values",
							expr: &zeroOrMoreExpr{
								pos: position{line: 307, col: 26, offset: 7031},
								expr: &seqExpr{
									pos: position{line: 307, col: 27, offset: 7032},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 307, col: 27, offset: 7032},
											name: "ConstValue",
										},
										&ruleRefExpr{
											pos:  position{line: 307, col: 38, offset: 7043},
											name: "__",
										},
										&litMatcher{
											pos:        position{line: 307, col: 41, offset: 7046},
											val:        ":",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 307, col: 45, offset: 7050},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 307, col: 48, offset: 7053},
											name: "ConstValue",
										},
										&ruleRefExpr{
											pos:  position{line: 307, col: 59, offset: 7064},
											name: "__",
										},
										&choiceExpr{
											pos: position{line: 307, col: 63, offset: 7068},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 307, col: 63, offset: 7068},
													val:        ",",
													ignoreCase: false,
												},
												&andExpr{
													pos: position{line: 307, col: 69, offset: 7074},
													expr: &litMatcher{
														pos:        position{line: 307, col: 70, offset: 7075},
														val:        "}",
														ignoreCase: false,
													},
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 307, col: 75, offset: 7080},
											name: "__",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 307, col: 80, offset: 7085},
							val:        "}",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Literal",
			pos:  position{line: 323, col: 1, offset: 7331},
			expr: &actionExpr{
				pos: position{line: 323, col: 11, offset: 7343},
				run: (*parser).callonLiteral1,
				expr: &choiceExpr{
					pos: position{line: 323, col: 12, offset: 7344},
					alternatives: []interface{}{
						&seqExpr{
							pos: position{line: 323, col: 13, offset: 7345},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 323, col: 13, offset: 7345},
									val:        "\"",
									ignoreCase: false,
								},
								&zeroOrMoreExpr{
									pos: position{line: 323, col: 17, offset: 7349},
									expr: &choiceExpr{
										pos: position{line: 323, col: 18, offset: 7350},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 323, col: 18, offset: 7350},
												val:        "\\\"",
												ignoreCase: false,
											},
											&charClassMatcher{
												pos:        position{line: 323, col: 25, offset: 7357},
												val:        "[^\"]",
												chars:      []rune{'"'},
												ignoreCase: false,
												inverted:   true,
											},
										},
									},
								},
								&litMatcher{
									pos:        position{line: 323, col: 32, offset: 7364},
									val:        "\"",
									ignoreCase: false,
								},
							},
						},
						&seqExpr{
							pos: position{line: 323, col: 40, offset: 7372},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 323, col: 40, offset: 7372},
									val:        "'",
									ignoreCase: false,
								},
								&zeroOrMoreExpr{
									pos: position{line: 323, col: 45, offset: 7377},
									expr: &choiceExpr{
										pos: position{line: 323, col: 46, offset: 7378},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 323, col: 46, offset: 7378},
												val:        "\\'",
												ignoreCase: false,
											},
											&charClassMatcher{
												pos:        position{line: 323, col: 53, offset: 7385},
												val:        "[^']",
												chars:      []rune{'\''},
												ignoreCase: false,
												inverted:   true,
											},
										},
									},
								},
								&litMatcher{
									pos:        position{line: 323, col: 60, offset: 7392},
									val:        "'",
									ignoreCase: false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 330, col: 1, offset: 7593},
			expr: &actionExpr{
				pos: position{line: 330, col: 14, offset: 7608},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 330, col: 14, offset: 7608},
					exprs: []interface{}{
						&oneOrMoreExpr{
							pos: position{line: 330, col: 14, offset: 7608},
							expr: &choiceExpr{
								pos: position{line: 330, col: 15, offset: 7609},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 330, col: 15, offset: 7609},
										name: "Letter",
									},
									&litMatcher{
										pos:        position{line: 330, col: 24, offset: 7618},
										val:        "_",
										ignoreCase: false,
									},
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 330, col: 30, offset: 7624},
							expr: &choiceExpr{
								pos: position{line: 330, col: 31, offset: 7625},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 330, col: 31, offset: 7625},
										name: "Letter",
									},
									&ruleRefExpr{
										pos:  position{line: 330, col: 40, offset: 7634},
										name: "Digit",
									},
									&charClassMatcher{
										pos:        position{line: 330, col: 48, offset: 7642},
										val:        "[._]",
										chars:      []rune{'.', '_'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ListSeparator",
			pos:  position{line: 334, col: 1, offset: 7694},
			expr: &charClassMatcher{
				pos:        position{line: 334, col: 17, offset: 7712},
				val:        "[,;]",
				chars:      []rune{',', ';'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Letter",
			pos:  position{line: 335, col: 1, offset: 7717},
			expr: &charClassMatcher{
				pos:        position{line: 335, col: 10, offset: 7728},
				val:        "[A-Za-z]",
				ranges:     []rune{'A', 'Z', 'a', 'z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Digit",
			pos:  position{line: 336, col: 1, offset: 7737},
			expr: &charClassMatcher{
				pos:        position{line: 336, col: 9, offset: 7747},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "SourceChar",
			pos:  position{line: 340, col: 1, offset: 7758},
			expr: &anyMatcher{
				line: 340, col: 14, offset: 7773,
			},
		},
		{
			name: "Comment",
			pos:  position{line: 341, col: 1, offset: 7775},
			expr: &choiceExpr{
				pos: position{line: 341, col: 11, offset: 7787},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 341, col: 11, offset: 7787},
						name: "MultiLineComment",
					},
					&ruleRefExpr{
						pos:  position{line: 341, col: 30, offset: 7806},
						name: "SingleLineComment",
					},
				},
			},
		},
		{
			name: "MultiLineComment",
			pos:  position{line: 342, col: 1, offset: 7824},
			expr: &seqExpr{
				pos: position{line: 342, col: 20, offset: 7845},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 342, col: 20, offset: 7845},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 342, col: 25, offset: 7850},
						expr: &seqExpr{
							pos: position{line: 342, col: 27, offset: 7852},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 342, col: 27, offset: 7852},
									expr: &litMatcher{
										pos:        position{line: 342, col: 28, offset: 7853},
										val:        "*/",
										ignoreCase: false,
									},
								},
								&ruleRefExpr{
									pos:  position{line: 342, col: 33, offset: 7858},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 342, col: 47, offset: 7872},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "MultiLineCommentNoLineTerminator",
			pos:  position{line: 343, col: 1, offset: 7877},
			expr: &seqExpr{
				pos: position{line: 343, col: 36, offset: 7914},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 343, col: 36, offset: 7914},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 343, col: 41, offset: 7919},
						expr: &seqExpr{
							pos: position{line: 343, col: 43, offset: 7921},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 343, col: 43, offset: 7921},
									expr: &choiceExpr{
										pos: position{line: 343, col: 46, offset: 7924},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 343, col: 46, offset: 7924},
												val:        "*/",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 343, col: 53, offset: 7931},
												name: "EOL",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 343, col: 59, offset: 7937},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 343, col: 73, offset: 7951},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 344, col: 1, offset: 7956},
			expr: &choiceExpr{
				pos: position{line: 344, col: 21, offset: 7978},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 344, col: 22, offset: 7979},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 344, col: 22, offset: 7979},
								val:        "//",
								ignoreCase: false,
							},
							&zeroOrMoreExpr{
								pos: position{line: 344, col: 27, offset: 7984},
								expr: &seqExpr{
									pos: position{line: 344, col: 29, offset: 7986},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 344, col: 29, offset: 7986},
											expr: &ruleRefExpr{
												pos:  position{line: 344, col: 30, offset: 7987},
												name: "EOL",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 344, col: 34, offset: 7991},
											name: "SourceChar",
										},
									},
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 344, col: 52, offset: 8009},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 344, col: 52, offset: 8009},
								val:        "#",
								ignoreCase: false,
							},
							&zeroOrMoreExpr{
								pos: position{line: 344, col: 56, offset: 8013},
								expr: &seqExpr{
									pos: position{line: 344, col: 58, offset: 8015},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 344, col: 58, offset: 8015},
											expr: &ruleRefExpr{
												pos:  position{line: 344, col: 59, offset: 8016},
												name: "EOL",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 344, col: 63, offset: 8020},
											name: "SourceChar",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 346, col: 1, offset: 8036},
			expr: &zeroOrMoreExpr{
				pos: position{line: 346, col: 6, offset: 8043},
				expr: &choiceExpr{
					pos: position{line: 346, col: 8, offset: 8045},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 346, col: 8, offset: 8045},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 346, col: 21, offset: 8058},
							name: "EOL",
						},
						&ruleRefExpr{
							pos:  position{line: 346, col: 27, offset: 8064},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 347, col: 1, offset: 8075},
			expr: &zeroOrMoreExpr{
				pos: position{line: 347, col: 5, offset: 8081},
				expr: &choiceExpr{
					pos: position{line: 347, col: 7, offset: 8083},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 347, col: 7, offset: 8083},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 347, col: 20, offset: 8096},
							name: "MultiLineCommentNoLineTerminator",
						},
					},
				},
			},
		},
		{
			name: "WS",
			pos:  position{line: 348, col: 1, offset: 8132},
			expr: &zeroOrMoreExpr{
				pos: position{line: 348, col: 6, offset: 8139},
				expr: &ruleRefExpr{
					pos:  position{line: 348, col: 6, offset: 8139},
					name: "Whitespace",
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 350, col: 1, offset: 8152},
			expr: &charClassMatcher{
				pos:        position{line: 350, col: 14, offset: 8167},
				val:        "[ \\t\\r]",
				chars:      []rune{' ', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOL",
			pos:  position{line: 351, col: 1, offset: 8175},
			expr: &litMatcher{
				pos:        position{line: 351, col: 7, offset: 8183},
				val:        "\n",
				ignoreCase: false,
			},
		},
		{
			name: "EOS",
			pos:  position{line: 352, col: 1, offset: 8188},
			expr: &choiceExpr{
				pos: position{line: 352, col: 7, offset: 8196},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 352, col: 7, offset: 8196},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 352, col: 7, offset: 8196},
								name: "__",
							},
							&litMatcher{
								pos:        position{line: 352, col: 10, offset: 8199},
								val:        ";",
								ignoreCase: false,
							},
						},
					},
					&seqExpr{
						pos: position{line: 352, col: 16, offset: 8205},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 352, col: 16, offset: 8205},
								name: "_",
							},
							&zeroOrOneExpr{
								pos: position{line: 352, col: 18, offset: 8207},
								expr: &ruleRefExpr{
									pos:  position{line: 352, col: 18, offset: 8207},
									name: "SingleLineComment",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 352, col: 37, offset: 8226},
								name: "EOL",
							},
						},
					},
					&seqExpr{
						pos: position{line: 352, col: 43, offset: 8232},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 352, col: 43, offset: 8232},
								name: "__",
							},
							&ruleRefExpr{
								pos:  position{line: 352, col: 46, offset: 8235},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 354, col: 1, offset: 8240},
			expr: &notExpr{
				pos: position{line: 354, col: 7, offset: 8248},
				expr: &anyMatcher{
					line: 354, col: 8, offset: 8249,
				},
			},
		},
	},
}

func (c *current) onGrammar1(statements interface{}) (interface{}, error) {
	thrift := &Thrift{
		Includes:   make(map[string]string),
		Namespaces: make(map[string]string),
		Typedefs:   make(map[string]*Type),
		Constants:  make(map[string]*Constant),
		Enums:      make(map[string]*Enum),
		Structs:    make(map[string]*Struct),
		Exceptions: make(map[string]*Struct),
		Services:   make(map[string]*Service),
	}
	stmts := toIfaceSlice(statements)
	for _, st := range stmts {
		switch v := st.([]interface{})[0].(type) {
		case *namespace:
			thrift.Namespaces[v.scope] = v.namespace
		case *Constant:
			thrift.Constants[v.Name] = v
		case *Enum:
			thrift.Enums[v.Name] = v
		case *typeDef:
			thrift.Typedefs[v.name] = v.typ
		case *Struct:
			thrift.Structs[v.Name] = v
		case exception:
			thrift.Exceptions[v.Name] = (*Struct)(v)
		case *Service:
			thrift.Services[v.Name] = v
		case include:
			name := string(v)
			if ix := strings.LastIndex(name, "."); ix > 0 {
				name = name[:ix]
			}
			thrift.Includes[name] = string(v)
		default:
			return nil, fmt.Errorf("parser: unknown value %#v", v)
		}
	}
	return thrift, nil
}

func (p *parser) callonGrammar1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGrammar1(stack["statements"])
}

func (c *current) onSyntaxError1() (interface{}, error) {
	return nil, errors.New("parser: syntax error")
}

func (p *parser) callonSyntaxError1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSyntaxError1()
}

func (c *current) onInclude1(file interface{}) (interface{}, error) {
	return include(file.(string)), nil
}

func (p *parser) callonInclude1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInclude1(stack["file"])
}

func (c *current) onNamespace1(scope, ns interface{}) (interface{}, error) {
	return &namespace{
		scope:     ifaceSliceToString(scope),
		namespace: string(ns.(Identifier)),
	}, nil
}

func (p *parser) callonNamespace1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNamespace1(stack["scope"], stack["ns"])
}

func (c *current) onConst1(typ, name, value interface{}) (interface{}, error) {
	return &Constant{
		Name:  string(name.(Identifier)),
		Type:  typ.(*Type),
		Value: value,
	}, nil
}

func (p *parser) callonConst1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConst1(stack["typ"], stack["name"], stack["value"])
}

func (c *current) onEnum1(name, values interface{}) (interface{}, error) {
	vs := toIfaceSlice(values)
	en := &Enum{
		Name:   string(name.(Identifier)),
		Values: make(map[string]*EnumValue, len(vs)),
	}
	// Assigns numbers in order. This will behave badly if some values are
	// defined and other are not, but I think that's ok since that's a silly
	// thing to do.
	next := 0
	for _, v := range vs {
		ev := v.([]interface{})[0].(*EnumValue)
		if ev.Value < 0 {
			ev.Value = next
		}
		if ev.Value >= next {
			next = ev.Value + 1
		}
		en.Values[ev.Name] = ev
	}
	return en, nil
}

func (p *parser) callonEnum1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEnum1(stack["name"], stack["values"])
}

func (c *current) onEnumValue1(name, value interface{}) (interface{}, error) {
	ev := &EnumValue{
		Name:  string(name.(Identifier)),
		Value: -1,
	}
	if value != nil {
		ev.Value = int(value.([]interface{})[2].(int64))
	}
	return ev, nil
}

func (p *parser) callonEnumValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEnumValue1(stack["name"], stack["value"])
}

func (c *current) onTypeDef1(typ, name interface{}) (interface{}, error) {
	return &typeDef{
		name: string(name.(Identifier)),
		typ:  typ.(*Type),
	}, nil
}

func (p *parser) callonTypeDef1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeDef1(stack["typ"], stack["name"])
}

func (c *current) onStruct1(st interface{}) (interface{}, error) {
	return st.(*Struct), nil
}

func (p *parser) callonStruct1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStruct1(stack["st"])
}

func (c *current) onException1(st interface{}) (interface{}, error) {
	return exception(st.(*Struct)), nil
}

func (p *parser) callonException1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onException1(stack["st"])
}

func (c *current) onStructLike1(name, fields interface{}) (interface{}, error) {
	st := &Struct{
		Name: string(name.(Identifier)),
	}
	if fields != nil {
		st.Fields = fields.([]*Field)
	}
	return st, nil
}

func (p *parser) callonStructLike1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStructLike1(stack["name"], stack["fields"])
}

func (c *current) onFieldList1(fields interface{}) (interface{}, error) {
	fs := fields.([]interface{})
	flds := make([]*Field, len(fs))
	for i, f := range fs {
		flds[i] = f.([]interface{})[0].(*Field)
	}
	return flds, nil
}

func (p *parser) callonFieldList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldList1(stack["fields"])
}

func (c *current) onField1(id, req, typ, name, def interface{}) (interface{}, error) {
	f := &Field{
		ID:   int(id.(int64)),
		Name: string(name.(Identifier)),
		Type: typ.(*Type),
	}
	if req != nil && !req.(bool) {
		f.Optional = true
	}
	if def != nil {
		f.Default = def.([]interface{})[2]
	}
	return f, nil
}

func (p *parser) callonField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["id"], stack["req"], stack["typ"], stack["name"], stack["def"])
}

func (c *current) onFieldReq1() (interface{}, error) {
	return !bytes.Equal(c.text, []byte("optional")), nil
}

func (p *parser) callonFieldReq1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldReq1()
}

func (c *current) onService1(name, extends, methods interface{}) (interface{}, error) {
	ms := methods.([]interface{})
	svc := &Service{
		Name:    string(name.(Identifier)),
		Methods: make(map[string]*Method, len(ms)),
	}
	if extends != nil {
		svc.Extends = string(extends.([]interface{})[2].(Identifier))
	}
	for _, m := range ms {
		mt := m.([]interface{})[0].(*Method)
		svc.Methods[mt.Name] = mt
	}
	return svc, nil
}

func (p *parser) callonService1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onService1(stack["name"], stack["extends"], stack["methods"])
}

func (c *current) onEndOfServiceError1() (interface{}, error) {
	return nil, errors.New("parser: expected end of service")
}

func (p *parser) callonEndOfServiceError1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEndOfServiceError1()
}

func (c *current) onFunction1(oneway, typ, name, arguments, exceptions interface{}) (interface{}, error) {
	m := &Method{
		Name: string(name.(Identifier)),
	}
	t := typ.(*Type)
	if t.Name != "void" {
		m.ReturnType = t
	}
	if oneway != nil {
		m.Oneway = true
	}
	if arguments != nil {
		m.Arguments = arguments.([]*Field)
	}
	if exceptions != nil {
		m.Exceptions = exceptions.([]*Field)
		for _, e := range m.Exceptions {
			e.Optional = true
		}
	}
	return m, nil
}

func (p *parser) callonFunction1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunction1(stack["oneway"], stack["typ"], stack["name"], stack["arguments"], stack["exceptions"])
}

func (c *current) onFunctionType1(typ interface{}) (interface{}, error) {
	if t, ok := typ.(*Type); ok {
		return t, nil
	}
	return &Type{Name: string(c.text)}, nil
}

func (p *parser) callonFunctionType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionType1(stack["typ"])
}

func (c *current) onThrows1(exceptions interface{}) (interface{}, error) {
	return exceptions, nil
}

func (p *parser) callonThrows1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onThrows1(stack["exceptions"])
}

func (c *current) onFieldType1(typ interface{}) (interface{}, error) {
	if t, ok := typ.(Identifier); ok {
		return &Type{Name: string(t)}, nil
	}
	return typ, nil
}

func (p *parser) callonFieldType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldType1(stack["typ"])
}

func (c *current) onDefinitionType1(typ interface{}) (interface{}, error) {
	return typ, nil
}

func (p *parser) callonDefinitionType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefinitionType1(stack["typ"])
}

func (c *current) onBaseType1() (interface{}, error) {
	return &Type{Name: string(c.text)}, nil
}

func (p *parser) callonBaseType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBaseType1()
}

func (c *current) onContainerType1(typ interface{}) (interface{}, error) {
	return typ, nil
}

func (p *parser) callonContainerType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onContainerType1(stack["typ"])
}

func (c *current) onMapType1(key, value interface{}) (interface{}, error) {
	return &Type{
		Name:      "map",
		KeyType:   key.(*Type),
		ValueType: value.(*Type),
	}, nil
}

func (p *parser) callonMapType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMapType1(stack["key"], stack["value"])
}

func (c *current) onSetType1(typ interface{}) (interface{}, error) {
	return &Type{
		Name:      "set",
		ValueType: typ.(*Type),
	}, nil
}

func (p *parser) callonSetType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSetType1(stack["typ"])
}

func (c *current) onListType1(typ interface{}) (interface{}, error) {
	return &Type{
		Name:      "list",
		ValueType: typ.(*Type),
	}, nil
}

func (p *parser) callonListType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onListType1(stack["typ"])
}

func (c *current) onCppType1(cppType interface{}) (interface{}, error) {
	return cppType, nil
}

func (p *parser) callonCppType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCppType1(stack["cppType"])
}

func (c *current) onIntConstant1() (interface{}, error) {
	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonIntConstant1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntConstant1()
}

func (c *current) onDoubleConstant1() (interface{}, error) {
	return strconv.ParseFloat(string(c.text), 64)
}

func (p *parser) callonDoubleConstant1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoubleConstant1()
}

func (c *current) onConstList1(values interface{}) (interface{}, error) {
	valueSlice := values.([]interface{})
	vs := make([]interface{}, len(valueSlice))
	for i, v := range valueSlice {
		vs[i] = v.([]interface{})[0]
	}
	return vs, nil
}

func (p *parser) callonConstList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstList1(stack["values"])
}

func (c *current) onConstMap1(values interface{}) (interface{}, error) {
	if values == nil {
		return nil, nil
	}
	vals := values.([]interface{})
	kvs := make([]KeyValue, len(vals))
	for i, kv := range vals {
		v := kv.([]interface{})
		kvs[i] = KeyValue{
			Key:   v[0],
			Value: v[4],
		}
	}
	return kvs, nil
}

func (p *parser) callonConstMap1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstMap1(stack["values"])
}

func (c *current) onLiteral1() (interface{}, error) {
	if len(c.text) != 0 && c.text[0] == '\'' {
		return strconv.Unquote(`"` + strings.Replace(string(c.text[1:len(c.text)-1]), `\'`, `'`, -1) + `"`)
	}
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonLiteral1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLiteral1()
}

func (c *current) onIdentifier1() (interface{}, error) {
	return Identifier(string(c.text)), nil
}

func (p *parser) callonIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errNoMatch is returned if no match could be found.
	errNoMatch = errors.New("no match found")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (interface{}, error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match
}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos        position
	val        string
	chars      []rune
	ranges     []rune
	classes    []*unicode.RangeTable
	ignoreCase bool
	inverted   bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner  error
	pos    position
	prefix string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
	}
	p.setOptions(opts)
	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	recover bool
	debug   bool
	depth   int

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// stats
	exprCnt int
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position)
}

func (p *parser) addErrAt(err error, pos position) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, prefix: buf.String()}
	p.errs.add(pe)
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError {
		if n > 0 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	// start rule is rule [0]
	p.read() // advance to first rune
	val, ok := p.parseRule(g.rules[0])
	if !ok {
		if len(*p.errs) == 0 {
			// make sure this doesn't go out silently
			p.addErr(errNoMatch)
		}
		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint
	var ok bool

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.exprCnt++
	var val interface{}
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position)
		}
		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restore(pt)
	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn != utf8.RuneError {
		start := p.pt
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	// can't match EOF
	if cur == utf8.RuneError {
		return nil, false
	}
	start := p.pt
	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for _, alt := range ch.alternatives {
		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(not.expr)
	p.popV()
	p.restore(pt)
	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	var vals []interface{}

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
