// DO NOT EDIT. Code generated by pigeon, run "go generate" to update.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

type namespace struct {
	scope     string
	namespace string
}

type exception *Struct

type union *Struct

type include string

func toIfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

func ifaceSliceToString(v interface{}) string {
	ifs := toIfaceSlice(v)
	b := make([]byte, len(ifs))
	for i, v := range ifs {
		b[i] = v.([]uint8)[0]
	}
	return string(b)
}

// toStruct converts a union to a struct with all fields optional.
func unionToStruct(u union) *Struct {
	st := (*Struct)(u)
	for _, f := range st.Fields {
		f.Optional = true
	}
	return st
}

func toAnnotations(v interface{}) []*Annotation {
	if v == nil {
		return nil
	}
	return v.([]*Annotation)
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Grammar",
			pos:  position{line: 56, col: 1, offset: 860},
			expr: &actionExpr{
				pos: position{line: 56, col: 11, offset: 872},
				run: (*parser).callonGrammar1,
				expr: &seqExpr{
					pos: position{line: 56, col: 11, offset: 872},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 56, col: 11, offset: 872},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 56, col: 14, offset: 875},
							label: "statements",
							expr: &zeroOrMoreExpr{
								pos: position{line: 56, col: 25, offset: 886},
								expr: &seqExpr{
									pos: position{line: 56, col: 27, offset: 888},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 56, col: 27, offset: 888},
											name: "Statement",
										},
										&ruleRefExpr{
											pos:  position{line: 56, col: 37, offset: 898},
											name: "__",
										},
									},
								},
							},
						},
						&choiceExpr{
							pos: position{line: 56, col: 44, offset: 905},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 56, col: 44, offset: 905},
									name: "EOF",
								},
								&ruleRefExpr{
									pos:  position{line: 56, col: 50, offset: 911},
									name: "SyntaxError",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SyntaxError",
			pos:  position{line: 100, col: 1, offset: 2081},
			expr: &actionExpr{
				pos: position{line: 100, col: 15, offset: 2097},
				run: (*parser).callonSyntaxError1,
				expr: &anyMatcher{
					line: 100, col: 15, offset: 2097,
				},
			},
		},
		{
			name: "Include",
			pos:  position{line: 104, col: 1, offset: 2152},
			expr: &actionExpr{
				pos: position{line: 104, col: 11, offset: 2164},
				run: (*parser).callonInclude1,
				expr: &seqExpr{
					pos: position{line: 104, col: 11, offset: 2164},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 104, col: 11, offset: 2164},
							val:        "include",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 104, col: 21, offset: 2174},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 104, col: 23, offset: 2176},
							label: "file",
							expr: &ruleRefExpr{
								pos:  position{line: 104, col: 28, offset: 2181},
								name: "Literal",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 104, col: 36, offset: 2189},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Statement",
			pos:  position{line: 108, col: 1, offset: 2234},
			expr: &choiceExpr{
				pos: position{line: 108, col: 13, offset: 2248},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 108, col: 13, offset: 2248},
						name: "Include",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 23, offset: 2258},
						name: "Namespace",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 35, offset: 2270},
						name: "Const",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 43, offset: 2278},
						name: "Enum",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 50, offset: 2285},
						name: "TypeDef",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 60, offset: 2295},
						name: "Struct",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 69, offset: 2304},
						name: "Exception",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 81, offset: 2316},
						name: "Union",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 89, offset: 2324},
						name: "Service",
					},
				},
			},
		},
		{
			name: "Namespace",
			pos:  position{line: 110, col: 1, offset: 2333},
			expr: &actionExpr{
				pos: position{line: 110, col: 13, offset: 2347},
				run: (*parser).callonNamespace1,
				expr: &seqExpr{
					pos: position{line: 110, col: 13, offset: 2347},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 110, col: 13, offset: 2347},
							val:        "namespace",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 110, col: 25, offset: 2359},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 110, col: 27, offset: 2361},
							label: "scope",
							expr: &oneOrMoreExpr{
								pos: position{line: 110, col: 33, offset: 2367},
								expr: &charClassMatcher{
									pos:        position{line: 110, col: 33, offset: 2367},
									val:        "[a-z.-]",
									chars:      []rune{'.', '-'},
									ranges:     []rune{'a', 'z'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 110, col: 42, offset: 2376},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 110, col: 44, offset: 2378},
							label: "ns",
							expr: &ruleRefExpr{
								pos:  position{line: 110, col: 47, offset: 2381},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 110, col: 58, offset: 2392},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Const",
			pos:  position{line: 117, col: 1, offset: 2503},
			expr: &actionExpr{
				pos: position{line: 117, col: 9, offset: 2513},
				run: (*parser).callonConst1,
				expr: &seqExpr{
					pos: position{line: 117, col: 9, offset: 2513},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 117, col: 9, offset: 2513},
							val:        "const",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 17, offset: 2521},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 117, col: 19, offset: 2523},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 23, offset: 2527},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 33, offset: 2537},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 117, col: 35, offset: 2539},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 40, offset: 2544},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 51, offset: 2555},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 117, col: 54, offset: 2558},
							val:        "=",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 58, offset: 2562},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 117, col: 61, offset: 2565},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 67, offset: 2571},
								name: "ConstValue",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 78, offset: 2582},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Enum",
			pos:  position{line: 125, col: 1, offset: 2690},
			expr: &actionExpr{
				pos: position{line: 125, col: 8, offset: 2699},
				run: (*parser).callonEnum1,
				expr: &seqExpr{
					pos: position{line: 125, col: 8, offset: 2699},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 125, col: 8, offset: 2699},
							val:        "enum",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 15, offset: 2706},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 125, col: 17, offset: 2708},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 22, offset: 2713},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 33, offset: 2724},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 125, col: 36, offset: 2727},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 40, offset: 2731},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 125, col: 43, offset: 2734},
							label: "values",
							expr: &zeroOrMoreExpr{
								pos: position{line: 125, col: 50, offset: 2741},
								expr: &seqExpr{
									pos: position{line: 125, col: 51, offset: 2742},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 125, col: 51, offset: 2742},
											name: "EnumValue",
										},
										&ruleRefExpr{
											pos:  position{line: 125, col: 61, offset: 2752},
											name: "__",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 125, col: 66, offset: 2757},
							val:        "}",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 70, offset: 2761},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 125, col: 73, offset: 2764},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 125, col: 85, offset: 2776},
								expr: &ruleRefExpr{
									pos:  position{line: 125, col: 85, offset: 2776},
									name: "TypeAnnotations",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 102, offset: 2793},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "EnumValue",
			pos:  position{line: 149, col: 1, offset: 3352},
			expr: &actionExpr{
				pos: position{line: 149, col: 13, offset: 3366},
				run: (*parser).callonEnumValue1,
				expr: &seqExpr{
					pos: position{line: 149, col: 13, offset: 3366},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 149, col: 13, offset: 3366},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 149, col: 18, offset: 3371},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 149, col: 29, offset: 3382},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 149, col: 31, offset: 3384},
							label: "value",
							expr: &zeroOrOneExpr{
								pos: position{line: 149, col: 37, offset: 3390},
								expr: &seqExpr{
									pos: position{line: 149, col: 38, offset: 3391},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 149, col: 38, offset: 3391},
											val:        "=",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 149, col: 42, offset: 3395},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 149, col: 44, offset: 3397},
											name: "IntConstant",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 149, col: 58, offset: 3411},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 149, col: 61, offset: 3414},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 149, col: 73, offset: 3426},
								expr: &ruleRefExpr{
									pos:  position{line: 149, col: 73, offset: 3426},
									name: "TypeAnnotations",
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 149, col: 90, offset: 3443},
							expr: &ruleRefExpr{
								pos:  position{line: 149, col: 90, offset: 3443},
								name: "ListSeparator",
							},
						},
					},
				},
			},
		},
		{
			name: "TypeDef",
			pos:  position{line: 161, col: 1, offset: 3665},
			expr: &actionExpr{
				pos: position{line: 161, col: 11, offset: 3677},
				run: (*parser).callonTypeDef1,
				expr: &seqExpr{
					pos: position{line: 161, col: 11, offset: 3677},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 161, col: 11, offset: 3677},
							val:        "typedef",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 161, col: 21, offset: 3687},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 161, col: 23, offset: 3689},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 161, col: 27, offset: 3693},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 161, col: 37, offset: 3703},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 161, col: 39, offset: 3705},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 161, col: 44, offset: 3710},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 161, col: 55, offset: 3721},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 161, col: 57, offset: 3723},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 161, col: 69, offset: 3735},
								expr: &ruleRefExpr{
									pos:  position{line: 161, col: 69, offset: 3735},
									name: "TypeAnnotations",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 161, col: 86, offset: 3752},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Struct",
			pos:  position{line: 170, col: 1, offset: 3888},
			expr: &actionExpr{
				pos: position{line: 170, col: 10, offset: 3899},
				run: (*parser).callonStruct1,
				expr: &seqExpr{
					pos: position{line: 170, col: 10, offset: 3899},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 170, col: 10, offset: 3899},
							val:        "struct",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 170, col: 19, offset: 3908},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 170, col: 21, offset: 3910},
							label: "st",
							expr: &ruleRefExpr{
								pos:  position{line: 170, col: 24, offset: 3913},
								name: "StructLike",
							},
						},
					},
				},
			},
		},
		{
			name: "Exception",
			pos:  position{line: 171, col: 1, offset: 3953},
			expr: &actionExpr{
				pos: position{line: 171, col: 13, offset: 3967},
				run: (*parser).callonException1,
				expr: &seqExpr{
					pos: position{line: 171, col: 13, offset: 3967},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 171, col: 13, offset: 3967},
							val:        "exception",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 25, offset: 3979},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 171, col: 27, offset: 3981},
							label: "st",
							expr: &ruleRefExpr{
								pos:  position{line: 171, col: 30, offset: 3984},
								name: "StructLike",
							},
						},
					},
				},
			},
		},
		{
			name: "Union",
			pos:  position{line: 172, col: 1, offset: 4035},
			expr: &actionExpr{
				pos: position{line: 172, col: 9, offset: 4045},
				run: (*parser).callonUnion1,
				expr: &seqExpr{
					pos: position{line: 172, col: 9, offset: 4045},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 172, col: 9, offset: 4045},
							val:        "union",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 172, col: 17, offset: 4053},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 172, col: 19, offset: 4055},
							label: "st",
							expr: &ruleRefExpr{
								pos:  position{line: 172, col: 22, offset: 4058},
								name: "StructLike",
							},
						},
					},
				},
			},
		},
		{
			name: "StructLike",
			pos:  position{line: 173, col: 1, offset: 4105},
			expr: &actionExpr{
				pos: position{line: 173, col: 14, offset: 4120},
				run: (*parser).callonStructLike1,
				expr: &seqExpr{
					pos: position{line: 173, col: 14, offset: 4120},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 173, col: 14, offset: 4120},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 173, col: 19, offset: 4125},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 173, col: 30, offset: 4136},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 173, col: 33, offset: 4139},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 173, col: 37, offset: 4143},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 173, col: 40, offset: 4146},
							label: "fields",
							expr: &ruleRefExpr{
								pos:  position{line: 173, col: 47, offset: 4153},
								name: "FieldList",
							},
						},
						&litMatcher{
							pos:        position{line: 173, col: 57, offset: 4163},
							val:        "}",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 173, col: 61, offset: 4167},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "FieldList",
			pos:  position{line: 183, col: 1, offset: 4301},
			expr: &actionExpr{
				pos: position{line: 183, col: 13, offset: 4315},
				run: (*parser).callonFieldList1,
				expr: &labeledExpr{
					pos:   position{line: 183, col: 13, offset: 4315},
					label: "fields",
					expr: &zeroOrMoreExpr{
						pos: position{line: 183, col: 20, offset: 4322},
						expr: &seqExpr{
							pos: position{line: 183, col: 21, offset: 4323},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 183, col: 21, offset: 4323},
									name: "Field",
								},
								&ruleRefExpr{
									pos:  position{line: 183, col: 27, offset: 4329},
									name: "__",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Field",
			pos:  position{line: 192, col: 1, offset: 4489},
			expr: &actionExpr{
				pos: position{line: 192, col: 9, offset: 4499},
				run: (*parser).callonField1,
				expr: &seqExpr{
					pos: position{line: 192, col: 9, offset: 4499},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 192, col: 9, offset: 4499},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 192, col: 12, offset: 4502},
								name: "IntConstant",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 192, col: 24, offset: 4514},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 192, col: 26, offset: 4516},
							val:        ":",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 192, col: 30, offset: 4520},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 192, col: 32, offset: 4522},
							label: "req",
							expr: &zeroOrOneExpr{
								pos: position{line: 192, col: 36, offset: 4526},
								expr: &ruleRefExpr{
									pos:  position{line: 192, col: 36, offset: 4526},
									name: "FieldReq",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 192, col: 46, offset: 4536},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 192, col: 48, offset: 4538},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 192, col: 52, offset: 4542},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 192, col: 62, offset: 4552},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 192, col: 64, offset: 4554},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 192, col: 69, offset: 4559},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 192, col: 80, offset: 4570},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 192, col: 83, offset: 4573},
							label: "def",
							expr: &zeroOrOneExpr{
								pos: position{line: 192, col: 87, offset: 4577},
								expr: &seqExpr{
									pos: position{line: 192, col: 88, offset: 4578},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 192, col: 88, offset: 4578},
											val:        "=",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 192, col: 92, offset: 4582},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 192, col: 94, offset: 4584},
											name: "ConstValue",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 192, col: 107, offset: 4597},
							expr: &ruleRefExpr{
								pos:  position{line: 192, col: 107, offset: 4597},
								name: "ListSeparator",
							},
						},
					},
				},
			},
		},
		{
			name: "FieldReq",
			pos:  position{line: 207, col: 1, offset: 4857},
			expr: &actionExpr{
				pos: position{line: 207, col: 12, offset: 4870},
				run: (*parser).callonFieldReq1,
				expr: &choiceExpr{
					pos: position{line: 207, col: 13, offset: 4871},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 207, col: 13, offset: 4871},
							val:        "required",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 207, col: 26, offset: 4884},
							val:        "optional",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Service",
			pos:  position{line: 211, col: 1, offset: 4955},
			expr: &actionExpr{
				pos: position{line: 211, col: 11, offset: 4967},
				run: (*parser).callonService1,
				expr: &seqExpr{
					pos: position{line: 211, col: 11, offset: 4967},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 211, col: 11, offset: 4967},
							val:        "service",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 211, col: 21, offset: 4977},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 211, col: 23, offset: 4979},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 211, col: 28, offset: 4984},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 211, col: 39, offset: 4995},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 211, col: 41, offset: 4997},
							label: "extends",
							expr: &zeroOrOneExpr{
								pos: position{line: 211, col: 49, offset: 5005},
								expr: &seqExpr{
									pos: position{line: 211, col: 50, offset: 5006},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 211, col: 50, offset: 5006},
											val:        "extends",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 211, col: 60, offset: 5016},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 211, col: 63, offset: 5019},
											name: "Identifier",
										},
										&ruleRefExpr{
											pos:  position{line: 211, col: 74, offset: 5030},
											name: "__",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 211, col: 79, offset: 5035},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 211, col: 82, offset: 5038},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 211, col: 86, offset: 5042},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 211, col: 89, offset: 5045},
							label: "methods",
							expr: &zeroOrMoreExpr{
								pos: position{line: 211, col: 97, offset: 5053},
								expr: &seqExpr{
									pos: position{line: 211, col: 98, offset: 5054},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 211, col: 98, offset: 5054},
											name: "Function",
										},
										&ruleRefExpr{
											pos:  position{line: 211, col: 107, offset: 5063},
											name: "__",
										},
									},
								},
							},
						},
						&choiceExpr{
							pos: position{line: 211, col: 113, offset: 5069},
							alternatives: []interface{}{
								&litMatcher{
									pos:        position{line: 211, col: 113, offset: 5069},
									val:        "}",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 211, col: 119, offset: 5075},
									name: "EndOfServiceError",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 211, col: 138, offset: 5094},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "EndOfServiceError",
			pos:  position{line: 226, col: 1, offset: 5435},
			expr: &actionExpr{
				pos: position{line: 226, col: 21, offset: 5457},
				run: (*parser).callonEndOfServiceError1,
				expr: &anyMatcher{
					line: 226, col: 21, offset: 5457,
				},
			},
		},
		{
			name: "Function",
			pos:  position{line: 230, col: 1, offset: 5523},
			expr: &actionExpr{
				pos: position{line: 230, col: 12, offset: 5536},
				run: (*parser).callonFunction1,
				expr: &seqExpr{
					pos: position{line: 230, col: 12, offset: 5536},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 230, col: 12, offset: 5536},
							label: "oneway",
							expr: &zeroOrOneExpr{
								pos: position{line: 230, col: 19, offset: 5543},
								expr: &seqExpr{
									pos: position{line: 230, col: 20, offset: 5544},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 230, col: 20, offset: 5544},
											val:        "oneway",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 230, col: 29, offset: 5553},
											name: "__",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 230, col: 34, offset: 5558},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 230, col: 38, offset: 5562},
								name: "FunctionType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 230, col: 51, offset: 5575},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 230, col: 54, offset: 5578},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 230, col: 59, offset: 5583},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 230, col: 70, offset: 5594},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 230, col: 72, offset: 5596},
							val:        "(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 230, col: 76, offset: 5600},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 230, col: 79, offset: 5603},
							label: "arguments",
							expr: &ruleRefExpr{
								pos:  position{line: 230, col: 89, offset: 5613},
								name: "FieldList",
							},
						},
						&litMatcher{
							pos:        position{line: 230, col: 99, offset: 5623},
							val:        ")",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 230, col: 103, offset: 5627},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 230, col: 106, offset: 5630},
							label: "exceptions",
							expr: &zeroOrOneExpr{
								pos: position{line: 230, col: 117, offset: 5641},
								expr: &ruleRefExpr{
									pos:  position{line: 230, col: 117, offset: 5641},
									name: "Throws",
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 230, col: 125, offset: 5649},
							expr: &ruleRefExpr{
								pos:  position{line: 230, col: 125, offset: 5649},
								name: "ListSeparator",
							},
						},
					},
				},
			},
		},
		{
			name: "FunctionType",
			pos:  position{line: 253, col: 1, offset: 6030},
			expr: &actionExpr{
				pos: position{line: 253, col: 16, offset: 6047},
				run: (*parser).callonFunctionType1,
				expr: &labeledExpr{
					pos:   position{line: 253, col: 16, offset: 6047},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 253, col: 21, offset: 6052},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 253, col: 21, offset: 6052},
								val:        "void",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 253, col: 30, offset: 6061},
								name: "FieldType",
							},
						},
					},
				},
			},
		},
		{
			name: "Throws",
			pos:  position{line: 260, col: 1, offset: 6168},
			expr: &actionExpr{
				pos: position{line: 260, col: 10, offset: 6179},
				run: (*parser).callonThrows1,
				expr: &seqExpr{
					pos: position{line: 260, col: 10, offset: 6179},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 260, col: 10, offset: 6179},
							val:        "throws",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 260, col: 19, offset: 6188},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 260, col: 22, offset: 6191},
							val:        "(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 260, col: 26, offset: 6195},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 260, col: 29, offset: 6198},
							label: "exceptions",
							expr: &ruleRefExpr{
								pos:  position{line: 260, col: 40, offset: 6209},
								name: "FieldList",
							},
						},
						&litMatcher{
							pos:        position{line: 260, col: 50, offset: 6219},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "FieldType",
			pos:  position{line: 264, col: 1, offset: 6252},
			expr: &actionExpr{
				pos: position{line: 264, col: 13, offset: 6266},
				run: (*parser).callonFieldType1,
				expr: &labeledExpr{
					pos:   position{line: 264, col: 13, offset: 6266},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 264, col: 18, offset: 6271},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 264, col: 18, offset: 6271},
								name: "BaseType",
							},
							&ruleRefExpr{
								pos:  position{line: 264, col: 29, offset: 6282},
								name: "ContainerType",
							},
							&ruleRefExpr{
								pos:  position{line: 264, col: 45, offset: 6298},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "DefinitionType",
			pos:  position{line: 271, col: 1, offset: 6408},
			expr: &actionExpr{
				pos: position{line: 271, col: 18, offset: 6427},
				run: (*parser).callonDefinitionType1,
				expr: &labeledExpr{
					pos:   position{line: 271, col: 18, offset: 6427},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 271, col: 23, offset: 6432},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 271, col: 23, offset: 6432},
								name: "BaseType",
							},
							&ruleRefExpr{
								pos:  position{line: 271, col: 34, offset: 6443},
								name: "ContainerType",
							},
						},
					},
				},
			},
		},
		{
			name: "BaseType",
			pos:  position{line: 275, col: 1, offset: 6480},
			expr: &actionExpr{
				pos: position{line: 275, col: 12, offset: 6493},
				run: (*parser).callonBaseType1,
				expr: &seqExpr{
					pos: position{line: 275, col: 12, offset: 6493},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 275, col: 12, offset: 6493},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 275, col: 17, offset: 6498},
								name: "BaseTypeName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 275, col: 30, offset: 6511},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 275, col: 33, offset: 6514},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 275, col: 45, offset: 6526},
								expr: &ruleRefExpr{
									pos:  position{line: 275, col: 45, offset: 6526},
									name: "TypeAnnotations",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BaseTypeName",
			pos:  position{line: 282, col: 1, offset: 6637},
			expr: &actionExpr{
				pos: position{line: 282, col: 16, offset: 6654},
				run: (*parser).callonBaseTypeName1,
				expr: &choiceExpr{
					pos: position{line: 282, col: 17, offset: 6655},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 282, col: 17, offset: 6655},
							val:        "bool",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 282, col: 26, offset: 6664},
							val:        "byte",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 282, col: 35, offset: 6673},
							val:        "i16",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 282, col: 43, offset: 6681},
							val:        "i32",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 282, col: 51, offset: 6689},
							val:        "i64",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 282, col: 59, offset: 6697},
							val:        "double",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 282, col: 70, offset: 6708},
							val:        "string",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 282, col: 81, offset: 6719},
							val:        "binary",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "ContainerType",
			pos:  position{line: 286, col: 1, offset: 6763},
			expr: &actionExpr{
				pos: position{line: 286, col: 17, offset: 6781},
				run: (*parser).callonContainerType1,
				expr: &labeledExpr{
					pos:   position{line: 286, col: 17, offset: 6781},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 286, col: 22, offset: 6786},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 286, col: 22, offset: 6786},
								name: "MapType",
							},
							&ruleRefExpr{
								pos:  position{line: 286, col: 32, offset: 6796},
								name: "SetType",
							},
							&ruleRefExpr{
								pos:  position{line: 286, col: 42, offset: 6806},
								name: "ListType",
							},
						},
					},
				},
			},
		},
		{
			name: "MapType",
			pos:  position{line: 290, col: 1, offset: 6838},
			expr: &actionExpr{
				pos: position{line: 290, col: 11, offset: 6850},
				run: (*parser).callonMapType1,
				expr: &seqExpr{
					pos: position{line: 290, col: 11, offset: 6850},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 290, col: 11, offset: 6850},
							expr: &ruleRefExpr{
								pos:  position{line: 290, col: 11, offset: 6850},
								name: "CppType",
							},
						},
						&litMatcher{
							pos:        position{line: 290, col: 20, offset: 6859},
							val:        "map",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 290, col: 26, offset: 6865},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 290, col: 29, offset: 6868},
							val:        "<",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 290, col: 33, offset: 6872},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 290, col: 36, offset: 6875},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 290, col: 40, offset: 6879},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 290, col: 50, offset: 6889},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 290, col: 53, offset: 6892},
							val:        ",",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 290, col: 57, offset: 6896},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 290, col: 60, offset: 6899},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 290, col: 66, offset: 6905},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 290, col: 76, offset: 6915},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 290, col: 79, offset: 6918},
							val:        ">",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 290, col: 83, offset: 6922},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 290, col: 86, offset: 6925},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 290, col: 98, offset: 6937},
								expr: &ruleRefExpr{
									pos:  position{line: 290, col: 98, offset: 6937},
									name: "TypeAnnotations",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SetType",
			pos:  position{line: 299, col: 1, offset: 7092},
			expr: &actionExpr{
				pos: position{line: 299, col: 11, offset: 7104},
				run: (*parser).callonSetType1,
				expr: &seqExpr{
					pos: position{line: 299, col: 11, offset: 7104},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 299, col: 11, offset: 7104},
							expr: &ruleRefExpr{
								pos:  position{line: 299, col: 11, offset: 7104},
								name: "CppType",
							},
						},
						&litMatcher{
							pos:        position{line: 299, col: 20, offset: 7113},
							val:        "set",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 299, col: 26, offset: 7119},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 299, col: 29, offset: 7122},
							val:        "<",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 299, col: 33, offset: 7126},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 299, col: 36, offset: 7129},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 299, col: 40, offset: 7133},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 299, col: 50, offset: 7143},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 299, col: 53, offset: 7146},
							val:        ">",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 299, col: 57, offset: 7150},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 299, col: 60, offset: 7153},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 299, col: 72, offset: 7165},
								expr: &ruleRefExpr{
									pos:  position{line: 299, col: 72, offset: 7165},
									name: "TypeAnnotations",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ListType",
			pos:  position{line: 307, col: 1, offset: 7294},
			expr: &actionExpr{
				pos: position{line: 307, col: 12, offset: 7307},
				run: (*parser).callonListType1,
				expr: &seqExpr{
					pos: position{line: 307, col: 12, offset: 7307},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 307, col: 12, offset: 7307},
							val:        "list",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 307, col: 19, offset: 7314},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 307, col: 22, offset: 7317},
							val:        "<",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 307, col: 26, offset: 7321},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 307, col: 29, offset: 7324},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 307, col: 33, offset: 7328},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 307, col: 43, offset: 7338},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 307, col: 46, offset: 7341},
							val:        ">",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 307, col: 50, offset: 7345},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 307, col: 53, offset: 7348},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 307, col: 65, offset: 7360},
								expr: &ruleRefExpr{
									pos:  position{line: 307, col: 65, offset: 7360},
									name: "TypeAnnotations",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CppType",
			pos:  position{line: 315, col: 1, offset: 7490},
			expr: &actionExpr{
				pos: position{line: 315, col: 11, offset: 7502},
				run: (*parser).callonCppType1,
				expr: &seqExpr{
					pos: position{line: 315, col: 11, offset: 7502},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 315, col: 11, offset: 7502},
							val:        "cpp_type",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 315, col: 22, offset: 7513},
							label: "cppType",
							expr: &ruleRefExpr{
								pos:  position{line: 315, col: 30, offset: 7521},
								name: "Literal",
							},
						},
					},
				},
			},
		},
		{
			name: "ConstValue",
			pos:  position{line: 319, col: 1, offset: 7555},
			expr: &choiceExpr{
				pos: position{line: 319, col: 14, offset: 7570},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 319, col: 14, offset: 7570},
						name: "Literal",
					},
					&ruleRefExpr{
						pos:  position{line: 319, col: 24, offset: 7580},
						name: "DoubleConstant",
					},
					&ruleRefExpr{
						pos:  position{line: 319, col: 41, offset: 7597},
						name: "IntConstant",
					},
					&ruleRefExpr{
						pos:  position{line: 319, col: 55, offset: 7611},
						name: "ConstMap",
					},
					&ruleRefExpr{
						pos:  position{line: 319, col: 66, offset: 7622},
						name: "ConstList",
					},
					&ruleRefExpr{
						pos:  position{line: 319, col: 78, offset: 7634},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "TypeAnnotations",
			pos:  position{line: 321, col: 1, offset: 7646},
			expr: &actionExpr{
				pos: position{line: 321, col: 19, offset: 7666},
				run: (*parser).callonTypeAnnotations1,
				expr: &seqExpr{
					pos: position{line: 321, col: 19, offset: 7666},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 321, col: 19, offset: 7666},
							val:        "(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 321, col: 23, offset: 7670},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 321, col: 26, offset: 7673},
							label: "annotations",
							expr: &zeroOrMoreExpr{
								pos: position{line: 321, col: 38, offset: 7685},
								expr: &ruleRefExpr{
									pos:  position{line: 321, col: 38, offset: 7685},
									name: "TypeAnnotation",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 321, col: 54, offset: 7701},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "TypeAnnotation",
			pos:  position{line: 329, col: 1, offset: 7847},
			expr: &actionExpr{
				pos: position{line: 329, col: 18, offset: 7866},
				run: (*parser).callonTypeAnnotation1,
				expr: &seqExpr{
					pos: position{line: 329, col: 18, offset: 7866},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 329, col: 18, offset: 7866},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 329, col: 23, offset: 7871},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 329, col: 34, offset: 7882},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 329, col: 36, offset: 7884},
							label: "value",
							expr: &zeroOrOneExpr{
								pos: position{line: 329, col: 42, offset: 7890},
								expr: &actionExpr{
									pos: position{line: 329, col: 43, offset: 7891},
									run: (*parser).callonTypeAnnotation8,
									expr: &seqExpr{
										pos: position{line: 329, col: 43, offset: 7891},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 329, col: 43, offset: 7891},
												val:        "=",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 329, col: 47, offset: 7895},
												name: "__",
											},
											&labeledExpr{
												pos:   position{line: 329, col: 50, offset: 7898},
												label: "value",
												expr: &ruleRefExpr{
													pos:  position{line: 329, col: 56, offset: 7904},
													name: "Literal",
												},
											},
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 329, col: 88, offset: 7936},
							expr: &ruleRefExpr{
								pos:  position{line: 329, col: 88, offset: 7936},
								name: "ListSeparator",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 329, col: 103, offset: 7951},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "IntConstant",
			pos:  position{line: 340, col: 1, offset: 8114},
			expr: &actionExpr{
				pos: position{line: 340, col: 15, offset: 8130},
				run: (*parser).callonIntConstant1,
				expr: &seqExpr{
					pos: position{line: 340, col: 15, offset: 8130},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 340, col: 15, offset: 8130},
							expr: &charClassMatcher{
								pos:        position{line: 340, col: 15, offset: 8130},
								val:        "[-+]",
								chars:      []rune{'-', '+'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 340, col: 21, offset: 8136},
							expr: &ruleRefExpr{
								pos:  position{line: 340, col: 21, offset: 8136},
								name: "Digit",
							},
						},
					},
				},
			},
		},
		{
			name: "DoubleConstant",
			pos:  position{line: 344, col: 1, offset: 8197},
			expr: &actionExpr{
				pos: position{line: 344, col: 18, offset: 8216},
				run: (*parser).callonDoubleConstant1,
				expr: &seqExpr{
					pos: position{line: 344, col: 18, offset: 8216},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 344, col: 18, offset: 8216},
							expr: &charClassMatcher{
								pos:        position{line: 344, col: 18, offset: 8216},
								val:        "[+-]",
								chars:      []rune{'+', '-'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 344, col: 24, offset: 8222},
							expr: &ruleRefExpr{
								pos:  position{line: 344, col: 24, offset: 8222},
								name: "Digit",
							},
						},
						&litMatcher{
							pos:        position{line: 344, col: 31, offset: 8229},
							val:        ".",
							ignoreCase: false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 344, col: 35, offset: 8233},
							expr: &ruleRefExpr{
								pos:  position{line: 344, col: 35, offset: 8233},
								name: "Digit",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 344, col: 42, offset: 8240},
							expr: &seqExpr{
								pos: position{line: 344, col: 44, offset: 8242},
								exprs: []interface{}{
									&charClassMatcher{
										pos:        position{line: 344, col: 44, offset: 8242},
										val:        "['Ee']",
										chars:      []rune{'\'', 'E', 'e', '\''},
										ignoreCase: false,
										inverted:   false,
									},
									&ruleRefExpr{
										pos:  position{line: 344, col: 51, offset: 8249},
										name: "IntConstant",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ConstList",
			pos:  position{line: 348, col: 1, offset: 8316},
			expr: &actionExpr{
				pos: position{line: 348, col: 13, offset: 8330},
				run: (*parser).callonConstList1,
				expr: &seqExpr{
					pos: position{line: 348, col: 13, offset: 8330},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 348, col: 13, offset: 8330},
							val:        "[",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 348, col: 17, offset: 8334},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 348, col: 20, offset: 8337},
							label: "values",
							expr: &zeroOrMoreExpr{
								pos: position{line: 348, col: 27, offset: 8344},
								expr: &seqExpr{
									pos: position{line: 348, col: 28, offset: 8345},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 348, col: 28, offset: 8345},
											name: "ConstValue",
										},
										&ruleRefExpr{
											pos:  position{line: 348, col: 39, offset: 8356},
											name: "__",
										},
										&zeroOrOneExpr{
											pos: position{line: 348, col: 42, offset: 8359},
											expr: &ruleRefExpr{
												pos:  position{line: 348, col: 42, offset: 8359},
												name: "ListSeparator",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 348, col: 57, offset: 8374},
											name: "__",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 348, col: 62, offset: 8379},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 348, col: 65, offset: 8382},
							val:        "]",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "ConstMap",
			pos:  position{line: 357, col: 1, offset: 8555},
			expr: &actionExpr{
				pos: position{line: 357, col: 12, offset: 8568},
				run: (*parser).callonConstMap1,
				expr: &seqExpr{
					pos: position{line: 357, col: 12, offset: 8568},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 357, col: 12, offset: 8568},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 357, col: 16, offset: 8572},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 357, col: 19, offset: 8575},
							label: "values",
							expr: &zeroOrMoreExpr{
								pos: position{line: 357, col: 26, offset: 8582},
								expr: &seqExpr{
									pos: position{line: 357, col: 27, offset: 8583},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 357, col: 27, offset: 8583},
											name: "ConstValue",
										},
										&ruleRefExpr{
											pos:  position{line: 357, col: 38, offset: 8594},
											name: "__",
										},
										&litMatcher{
											pos:        position{line: 357, col: 41, offset: 8597},
											val:        ":",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 357, col: 45, offset: 8601},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 357, col: 48, offset: 8604},
											name: "ConstValue",
										},
										&ruleRefExpr{
											pos:  position{line: 357, col: 59, offset: 8615},
											name: "__",
										},
										&choiceExpr{
											pos: position{line: 357, col: 63, offset: 8619},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 357, col: 63, offset: 8619},
													val:        ",",
													ignoreCase: false,
												},
												&andExpr{
													pos: position{line: 357, col: 69, offset: 8625},
													expr: &litMatcher{
														pos:        position{line: 357, col: 70, offset: 8626},
														val:        "}",
														ignoreCase: false,
													},
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 357, col: 75, offset: 8631},
											name: "__",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 357, col: 80, offset: 8636},
							val:        "}",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Literal",
			pos:  position{line: 373, col: 1, offset: 8882},
			expr: &actionExpr{
				pos: position{line: 373, col: 11, offset: 8894},
				run: (*parser).callonLiteral1,
				expr: &choiceExpr{
					pos: position{line: 373, col: 12, offset: 8895},
					alternatives: []interface{}{
						&seqExpr{
							pos: position{line: 373, col: 13, offset: 8896},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 373, col: 13, offset: 8896},
									val:        "\"",
									ignoreCase: false,
								},
								&zeroOrMoreExpr{
									pos: position{line: 373, col: 17, offset: 8900},
									expr: &choiceExpr{
										pos: position{line: 373, col: 18, offset: 8901},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 373, col: 18, offset: 8901},
												val:        "\\\"",
												ignoreCase: false,
											},
											&charClassMatcher{
												pos:        position{line: 373, col: 25, offset: 8908},
												val:        "[^\"]",
												chars:      []rune{'"'},
												ignoreCase: false,
												inverted:   true,
											},
										},
									},
								},
								&litMatcher{
									pos:        position{line: 373, col: 32, offset: 8915},
									val:        "\"",
									ignoreCase: false,
								},
							},
						},
						&seqExpr{
							pos: position{line: 373, col: 40, offset: 8923},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 373, col: 40, offset: 8923},
									val:        "'",
									ignoreCase: false,
								},
								&zeroOrMoreExpr{
									pos: position{line: 373, col: 45, offset: 8928},
									expr: &choiceExpr{
										pos: position{line: 373, col: 46, offset: 8929},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 373, col: 46, offset: 8929},
												val:        "\\'",
												ignoreCase: false,
											},
											&charClassMatcher{
												pos:        position{line: 373, col: 53, offset: 8936},
												val:        "[^']",
												chars:      []rune{'\''},
												ignoreCase: false,
												inverted:   true,
											},
										},
									},
								},
								&litMatcher{
									pos:        position{line: 373, col: 60, offset: 8943},
									val:        "'",
									ignoreCase: false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 380, col: 1, offset: 9144},
			expr: &actionExpr{
				pos: position{line: 380, col: 14, offset: 9159},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 380, col: 14, offset: 9159},
					exprs: []interface{}{
						&oneOrMoreExpr{
							pos: position{line: 380, col: 14, offset: 9159},
							expr: &choiceExpr{
								pos: position{line: 380, col: 15, offset: 9160},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 380, col: 15, offset: 9160},
										name: "Letter",
									},
									&litMatcher{
										pos:        position{line: 380, col: 24, offset: 9169},
										val:        "_",
										ignoreCase: false,
									},
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 380, col: 30, offset: 9175},
							expr: &choiceExpr{
								pos: position{line: 380, col: 31, offset: 9176},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 380, col: 31, offset: 9176},
										name: "Letter",
									},
									&ruleRefExpr{
										pos:  position{line: 380, col: 40, offset: 9185},
										name: "Digit",
									},
									&charClassMatcher{
										pos:        position{line: 380, col: 48, offset: 9193},
										val:        "[._]",
										chars:      []rune{'.', '_'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ListSeparator",
			pos:  position{line: 384, col: 1, offset: 9245},
			expr: &charClassMatcher{
				pos:        position{line: 384, col: 17, offset: 9263},
				val:        "[,;]",
				chars:      []rune{',', ';'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Letter",
			pos:  position{line: 385, col: 1, offset: 9268},
			expr: &charClassMatcher{
				pos:        position{line: 385, col: 10, offset: 9279},
				val:        "[A-Za-z]",
				ranges:     []rune{'A', 'Z', 'a', 'z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Digit",
			pos:  position{line: 386, col: 1, offset: 9288},
			expr: &charClassMatcher{
				pos:        position{line: 386, col: 9, offset: 9298},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "SourceChar",
			pos:  position{line: 390, col: 1, offset: 9309},
			expr: &anyMatcher{
				line: 390, col: 14, offset: 9324,
			},
		},
		{
			name: "Comment",
			pos:  position{line: 391, col: 1, offset: 9326},
			expr: &choiceExpr{
				pos: position{line: 391, col: 11, offset: 9338},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 391, col: 11, offset: 9338},
						name: "MultiLineComment",
					},
					&ruleRefExpr{
						pos:  position{line: 391, col: 30, offset: 9357},
						name: "SingleLineComment",
					},
				},
			},
		},
		{
			name: "MultiLineComment",
			pos:  position{line: 392, col: 1, offset: 9375},
			expr: &seqExpr{
				pos: position{line: 392, col: 20, offset: 9396},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 392, col: 20, offset: 9396},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 392, col: 25, offset: 9401},
						expr: &seqExpr{
							pos: position{line: 392, col: 27, offset: 9403},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 392, col: 27, offset: 9403},
									expr: &litMatcher{
										pos:        position{line: 392, col: 28, offset: 9404},
										val:        "*/",
										ignoreCase: false,
									},
								},
								&ruleRefExpr{
									pos:  position{line: 392, col: 33, offset: 9409},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 392, col: 47, offset: 9423},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "MultiLineCommentNoLineTerminator",
			pos:  position{line: 393, col: 1, offset: 9428},
			expr: &seqExpr{
				pos: position{line: 393, col: 36, offset: 9465},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 393, col: 36, offset: 9465},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 393, col: 41, offset: 9470},
						expr: &seqExpr{
							pos: position{line: 393, col: 43, offset: 9472},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 393, col: 43, offset: 9472},
									expr: &choiceExpr{
										pos: position{line: 393, col: 46, offset: 9475},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 393, col: 46, offset: 9475},
												val:        "*/",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 393, col: 53, offset: 9482},
												name: "EOL",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 393, col: 59, offset: 9488},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 393, col: 73, offset: 9502},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 394, col: 1, offset: 9507},
			expr: &choiceExpr{
				pos: position{line: 394, col: 21, offset: 9529},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 394, col: 22, offset: 9530},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 394, col: 22, offset: 9530},
								val:        "//",
								ignoreCase: false,
							},
							&zeroOrMoreExpr{
								pos: position{line: 394, col: 27, offset: 9535},
								expr: &seqExpr{
									pos: position{line: 394, col: 29, offset: 9537},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 394, col: 29, offset: 9537},
											expr: &ruleRefExpr{
												pos:  position{line: 394, col: 30, offset: 9538},
												name: "EOL",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 394, col: 34, offset: 9542},
											name: "SourceChar",
										},
									},
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 394, col: 52, offset: 9560},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 394, col: 52, offset: 9560},
								val:        "#",
								ignoreCase: false,
							},
							&zeroOrMoreExpr{
								pos: position{line: 394, col: 56, offset: 9564},
								expr: &seqExpr{
									pos: position{line: 394, col: 58, offset: 9566},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 394, col: 58, offset: 9566},
											expr: &ruleRefExpr{
												pos:  position{line: 394, col: 59, offset: 9567},
												name: "EOL",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 394, col: 63, offset: 9571},
											name: "SourceChar",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 396, col: 1, offset: 9587},
			expr: &zeroOrMoreExpr{
				pos: position{line: 396, col: 6, offset: 9594},
				expr: &choiceExpr{
					pos: position{line: 396, col: 8, offset: 9596},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 396, col: 8, offset: 9596},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 396, col: 21, offset: 9609},
							name: "EOL",
						},
						&ruleRefExpr{
							pos:  position{line: 396, col: 27, offset: 9615},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 397, col: 1, offset: 9626},
			expr: &zeroOrMoreExpr{
				pos: position{line: 397, col: 5, offset: 9632},
				expr: &choiceExpr{
					pos: position{line: 397, col: 7, offset: 9634},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 397, col: 7, offset: 9634},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 397, col: 20, offset: 9647},
							name: "MultiLineCommentNoLineTerminator",
						},
					},
				},
			},
		},
		{
			name: "WS",
			pos:  position{line: 398, col: 1, offset: 9683},
			expr: &zeroOrMoreExpr{
				pos: position{line: 398, col: 6, offset: 9690},
				expr: &ruleRefExpr{
					pos:  position{line: 398, col: 6, offset: 9690},
					name: "Whitespace",
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 400, col: 1, offset: 9703},
			expr: &charClassMatcher{
				pos:        position{line: 400, col: 14, offset: 9718},
				val:        "[ \\t\\r]",
				chars:      []rune{' ', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOL",
			pos:  position{line: 401, col: 1, offset: 9726},
			expr: &litMatcher{
				pos:        position{line: 401, col: 7, offset: 9734},
				val:        "\n",
				ignoreCase: false,
			},
		},
		{
			name: "EOS",
			pos:  position{line: 402, col: 1, offset: 9739},
			expr: &choiceExpr{
				pos: position{line: 402, col: 7, offset: 9747},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 402, col: 7, offset: 9747},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 402, col: 7, offset: 9747},
								name: "__",
							},
							&litMatcher{
								pos:        position{line: 402, col: 10, offset: 9750},
								val:        ";",
								ignoreCase: false,
							},
						},
					},
					&seqExpr{
						pos: position{line: 402, col: 16, offset: 9756},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 402, col: 16, offset: 9756},
								name: "_",
							},
							&zeroOrOneExpr{
								pos: position{line: 402, col: 18, offset: 9758},
								expr: &ruleRefExpr{
									pos:  position{line: 402, col: 18, offset: 9758},
									name: "SingleLineComment",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 402, col: 37, offset: 9777},
								name: "EOL",
							},
						},
					},
					&seqExpr{
						pos: position{line: 402, col: 43, offset: 9783},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 402, col: 43, offset: 9783},
								name: "__",
							},
							&ruleRefExpr{
								pos:  position{line: 402, col: 46, offset: 9786},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 404, col: 1, offset: 9791},
			expr: &notExpr{
				pos: position{line: 404, col: 7, offset: 9799},
				expr: &anyMatcher{
					line: 404, col: 8, offset: 9800,
				},
			},
		},
	},
}

func (c *current) onGrammar1(statements interface{}) (interface{}, error) {
	thrift := &Thrift{
		Includes:   make(map[string]string),
		Namespaces: make(map[string]string),
		Typedefs:   make(map[string]*Typedef),
		Constants:  make(map[string]*Constant),
		Enums:      make(map[string]*Enum),
		Structs:    make(map[string]*Struct),
		Exceptions: make(map[string]*Struct),
		Unions:     make(map[string]*Struct),
		Services:   make(map[string]*Service),
	}
	stmts := toIfaceSlice(statements)
	for _, st := range stmts {
		switch v := st.([]interface{})[0].(type) {
		case *namespace:
			thrift.Namespaces[v.scope] = v.namespace
		case *Constant:
			thrift.Constants[v.Name] = v
		case *Enum:
			thrift.Enums[v.Name] = v
		case *Typedef:
			thrift.Typedefs[v.Alias] = v
		case *Struct:
			thrift.Structs[v.Name] = v
		case exception:
			thrift.Exceptions[v.Name] = (*Struct)(v)
		case union:
			thrift.Unions[v.Name] = unionToStruct(v)
		case *Service:
			thrift.Services[v.Name] = v
		case include:
			name := filepath.Base(string(v))
			if ix := strings.LastIndex(name, "."); ix > 0 {
				name = name[:ix]
			}
			thrift.Includes[name] = string(v)
		default:
			return nil, fmt.Errorf("parser: unknown value %#v", v)
		}
	}
	return thrift, nil
}

func (p *parser) callonGrammar1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGrammar1(stack["statements"])
}

func (c *current) onSyntaxError1() (interface{}, error) {
	return nil, errors.New("parser: syntax error")
}

func (p *parser) callonSyntaxError1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSyntaxError1()
}

func (c *current) onInclude1(file interface{}) (interface{}, error) {
	return include(file.(string)), nil
}

func (p *parser) callonInclude1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInclude1(stack["file"])
}

func (c *current) onNamespace1(scope, ns interface{}) (interface{}, error) {
	return &namespace{
		scope:     ifaceSliceToString(scope),
		namespace: string(ns.(Identifier)),
	}, nil
}

func (p *parser) callonNamespace1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNamespace1(stack["scope"], stack["ns"])
}

func (c *current) onConst1(typ, name, value interface{}) (interface{}, error) {
	return &Constant{
		Name:  string(name.(Identifier)),
		Type:  typ.(*Type),
		Value: value,
	}, nil
}

func (p *parser) callonConst1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConst1(stack["typ"], stack["name"], stack["value"])
}

func (c *current) onEnum1(name, values, annotations interface{}) (interface{}, error) {
	vs := toIfaceSlice(values)
	en := &Enum{
		Name:        string(name.(Identifier)),
		Values:      make(map[string]*EnumValue, len(vs)),
		Annotations: toAnnotations(annotations),
	}
	// Assigns numbers in order. This will behave badly if some values are
	// defined and other are not, but I think that's ok since that's a silly
	// thing to do.
	next := 0
	for _, v := range vs {
		ev := v.([]interface{})[0].(*EnumValue)
		if ev.Value < 0 {
			ev.Value = next
		}
		if ev.Value >= next {
			next = ev.Value + 1
		}
		en.Values[ev.Name] = ev
	}
	return en, nil
}

func (p *parser) callonEnum1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEnum1(stack["name"], stack["values"], stack["annotations"])
}

func (c *current) onEnumValue1(name, value, annotations interface{}) (interface{}, error) {
	ev := &EnumValue{
		Name:        string(name.(Identifier)),
		Value:       -1,
		Annotations: toAnnotations(annotations),
	}
	if value != nil {
		ev.Value = int(value.([]interface{})[2].(int64))
	}
	return ev, nil
}

func (p *parser) callonEnumValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEnumValue1(stack["name"], stack["value"], stack["annotations"])
}

func (c *current) onTypeDef1(typ, name, annotations interface{}) (interface{}, error) {
	return &Typedef{
		Type: typ.(*Type),

		Alias:       string(name.(Identifier)),
		Annotations: toAnnotations(annotations),
	}, nil
}

func (p *parser) callonTypeDef1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeDef1(stack["typ"], stack["name"], stack["annotations"])
}

func (c *current) onStruct1(st interface{}) (interface{}, error) {
	return st.(*Struct), nil
}

func (p *parser) callonStruct1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStruct1(stack["st"])
}

func (c *current) onException1(st interface{}) (interface{}, error) {
	return exception(st.(*Struct)), nil
}

func (p *parser) callonException1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onException1(stack["st"])
}

func (c *current) onUnion1(st interface{}) (interface{}, error) {
	return union(st.(*Struct)), nil
}

func (p *parser) callonUnion1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnion1(stack["st"])
}

func (c *current) onStructLike1(name, fields interface{}) (interface{}, error) {
	st := &Struct{
		Name: string(name.(Identifier)),
	}
	if fields != nil {
		st.Fields = fields.([]*Field)
	}
	return st, nil
}

func (p *parser) callonStructLike1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStructLike1(stack["name"], stack["fields"])
}

func (c *current) onFieldList1(fields interface{}) (interface{}, error) {
	fs := fields.([]interface{})
	flds := make([]*Field, len(fs))
	for i, f := range fs {
		flds[i] = f.([]interface{})[0].(*Field)
	}
	return flds, nil
}

func (p *parser) callonFieldList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldList1(stack["fields"])
}

func (c *current) onField1(id, req, typ, name, def interface{}) (interface{}, error) {
	f := &Field{
		ID:   int(id.(int64)),
		Name: string(name.(Identifier)),
		Type: typ.(*Type),
	}
	if req != nil && !req.(bool) {
		f.Optional = true
	}
	if def != nil {
		f.Default = def.([]interface{})[2]
	}
	return f, nil
}

func (p *parser) callonField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["id"], stack["req"], stack["typ"], stack["name"], stack["def"])
}

func (c *current) onFieldReq1() (interface{}, error) {
	return !bytes.Equal(c.text, []byte("optional")), nil
}

func (p *parser) callonFieldReq1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldReq1()
}

func (c *current) onService1(name, extends, methods interface{}) (interface{}, error) {
	ms := methods.([]interface{})
	svc := &Service{
		Name:    string(name.(Identifier)),
		Methods: make(map[string]*Method, len(ms)),
	}
	if extends != nil {
		svc.Extends = string(extends.([]interface{})[2].(Identifier))
	}
	for _, m := range ms {
		mt := m.([]interface{})[0].(*Method)
		svc.Methods[mt.Name] = mt
	}
	return svc, nil
}

func (p *parser) callonService1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onService1(stack["name"], stack["extends"], stack["methods"])
}

func (c *current) onEndOfServiceError1() (interface{}, error) {
	return nil, errors.New("parser: expected end of service")
}

func (p *parser) callonEndOfServiceError1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEndOfServiceError1()
}

func (c *current) onFunction1(oneway, typ, name, arguments, exceptions interface{}) (interface{}, error) {
	m := &Method{
		Name: string(name.(Identifier)),
	}
	t := typ.(*Type)
	if t.Name != "void" {
		m.ReturnType = t
	}
	if oneway != nil {
		m.Oneway = true
	}
	if arguments != nil {
		m.Arguments = arguments.([]*Field)
	}
	if exceptions != nil {
		m.Exceptions = exceptions.([]*Field)
		for _, e := range m.Exceptions {
			e.Optional = true
		}
	}
	return m, nil
}

func (p *parser) callonFunction1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunction1(stack["oneway"], stack["typ"], stack["name"], stack["arguments"], stack["exceptions"])
}

func (c *current) onFunctionType1(typ interface{}) (interface{}, error) {
	if t, ok := typ.(*Type); ok {
		return t, nil
	}
	return &Type{Name: string(c.text)}, nil
}

func (p *parser) callonFunctionType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionType1(stack["typ"])
}

func (c *current) onThrows1(exceptions interface{}) (interface{}, error) {
	return exceptions, nil
}

func (p *parser) callonThrows1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onThrows1(stack["exceptions"])
}

func (c *current) onFieldType1(typ interface{}) (interface{}, error) {
	if t, ok := typ.(Identifier); ok {
		return &Type{Name: string(t)}, nil
	}
	return typ, nil
}

func (p *parser) callonFieldType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldType1(stack["typ"])
}

func (c *current) onDefinitionType1(typ interface{}) (interface{}, error) {
	return typ, nil
}

func (p *parser) callonDefinitionType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefinitionType1(stack["typ"])
}

func (c *current) onBaseType1(name, annotations interface{}) (interface{}, error) {
	return &Type{
		Name:        name.(string),
		Annotations: toAnnotations(annotations),
	}, nil
}

func (p *parser) callonBaseType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBaseType1(stack["name"], stack["annotations"])
}

func (c *current) onBaseTypeName1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonBaseTypeName1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBaseTypeName1()
}

func (c *current) onContainerType1(typ interface{}) (interface{}, error) {
	return typ, nil
}

func (p *parser) callonContainerType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onContainerType1(stack["typ"])
}

func (c *current) onMapType1(key, value, annotations interface{}) (interface{}, error) {
	return &Type{
		Name:        "map",
		KeyType:     key.(*Type),
		ValueType:   value.(*Type),
		Annotations: toAnnotations(annotations),
	}, nil
}

func (p *parser) callonMapType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMapType1(stack["key"], stack["value"], stack["annotations"])
}

func (c *current) onSetType1(typ, annotations interface{}) (interface{}, error) {
	return &Type{
		Name:        "set",
		ValueType:   typ.(*Type),
		Annotations: toAnnotations(annotations),
	}, nil
}

func (p *parser) callonSetType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSetType1(stack["typ"], stack["annotations"])
}

func (c *current) onListType1(typ, annotations interface{}) (interface{}, error) {
	return &Type{
		Name:        "list",
		ValueType:   typ.(*Type),
		Annotations: toAnnotations(annotations),
	}, nil
}

func (p *parser) callonListType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onListType1(stack["typ"], stack["annotations"])
}

func (c *current) onCppType1(cppType interface{}) (interface{}, error) {
	return cppType, nil
}

func (p *parser) callonCppType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCppType1(stack["cppType"])
}

func (c *current) onTypeAnnotations1(annotations interface{}) (interface{}, error) {
	var anns []*Annotation
	for _, ann := range annotations.([]interface{}) {
		anns = append(anns, ann.(*Annotation))
	}
	return anns, nil
}

func (p *parser) callonTypeAnnotations1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAnnotations1(stack["annotations"])
}

func (c *current) onTypeAnnotation8(value interface{}) (interface{}, error) {
	return value, nil
}

func (p *parser) callonTypeAnnotation8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAnnotation8(stack["value"])
}

func (c *current) onTypeAnnotation1(name, value interface{}) (interface{}, error) {
	var optValue string
	if value != nil {
		optValue = value.(string)
	}
	return &Annotation{
		Name:  string(name.(Identifier)),
		Value: optValue,
	}, nil
}

func (p *parser) callonTypeAnnotation1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAnnotation1(stack["name"], stack["value"])
}

func (c *current) onIntConstant1() (interface{}, error) {
	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonIntConstant1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntConstant1()
}

func (c *current) onDoubleConstant1() (interface{}, error) {
	return strconv.ParseFloat(string(c.text), 64)
}

func (p *parser) callonDoubleConstant1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoubleConstant1()
}

func (c *current) onConstList1(values interface{}) (interface{}, error) {
	valueSlice := values.([]interface{})
	vs := make([]interface{}, len(valueSlice))
	for i, v := range valueSlice {
		vs[i] = v.([]interface{})[0]
	}
	return vs, nil
}

func (p *parser) callonConstList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstList1(stack["values"])
}

func (c *current) onConstMap1(values interface{}) (interface{}, error) {
	if values == nil {
		return nil, nil
	}
	vals := values.([]interface{})
	kvs := make([]KeyValue, len(vals))
	for i, kv := range vals {
		v := kv.([]interface{})
		kvs[i] = KeyValue{
			Key:   v[0],
			Value: v[4],
		}
	}
	return kvs, nil
}

func (p *parser) callonConstMap1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstMap1(stack["values"])
}

func (c *current) onLiteral1() (interface{}, error) {
	if len(c.text) != 0 && c.text[0] == '\'' {
		return strconv.Unquote(`"` + strings.Replace(string(c.text[1:len(c.text)-1]), `\'`, `'`, -1) + `"`)
	}
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonLiteral1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLiteral1()
}

func (c *current) onIdentifier1() (interface{}, error) {
	return Identifier(string(c.text)), nil
}

func (p *parser) callonIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errNoMatch is returned if no match could be found.
	errNoMatch = errors.New("no match found")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (interface{}, error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match
}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos        position
	val        string
	chars      []rune
	ranges     []rune
	classes    []*unicode.RangeTable
	ignoreCase bool
	inverted   bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner  error
	pos    position
	prefix string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
	}
	p.setOptions(opts)
	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	recover bool
	debug   bool
	depth   int

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// stats
	exprCnt int
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position)
}

func (p *parser) addErrAt(err error, pos position) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, prefix: buf.String()}
	p.errs.add(pe)
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError {
		if n > 0 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	// start rule is rule [0]
	p.read() // advance to first rune
	val, ok := p.parseRule(g.rules[0])
	if !ok {
		if len(*p.errs) == 0 {
			// make sure this doesn't go out silently
			p.addErr(errNoMatch)
		}
		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint
	var ok bool

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.exprCnt++
	var val interface{}
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position)
		}
		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restore(pt)
	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn != utf8.RuneError {
		start := p.pt
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	// can't match EOF
	if cur == utf8.RuneError {
		return nil, false
	}
	start := p.pt
	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for _, alt := range ch.alternatives {
		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(not.expr)
	p.popV()
	p.restore(pt)
	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	var vals []interface{}

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
