// DO NOT EDIT. Code generated by pigeon, run "go generate" to update.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

type namespace struct {
	scope     string
	namespace string
}

type exception *Struct

type union *Struct

type include string

func toIfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

func ifaceSliceToString(v interface{}) string {
	ifs := toIfaceSlice(v)
	b := make([]byte, len(ifs))
	for i, v := range ifs {
		b[i] = v.([]uint8)[0]
	}
	return string(b)
}

// toStruct converts a union to a struct with all fields optional.
func unionToStruct(u union) *Struct {
	st := (*Struct)(u)
	for _, f := range st.Fields {
		f.Optional = true
	}
	return st
}

func toAnnotations(v interface{}) []*Annotation {
	if v == nil {
		return nil
	}
	return v.([]*Annotation)
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Grammar",
			pos:  position{line: 56, col: 1, offset: 860},
			expr: &actionExpr{
				pos: position{line: 56, col: 11, offset: 872},
				run: (*parser).callonGrammar1,
				expr: &seqExpr{
					pos: position{line: 56, col: 11, offset: 872},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 56, col: 11, offset: 872},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 56, col: 14, offset: 875},
							label: "statements",
							expr: &zeroOrMoreExpr{
								pos: position{line: 56, col: 25, offset: 886},
								expr: &seqExpr{
									pos: position{line: 56, col: 27, offset: 888},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 56, col: 27, offset: 888},
											name: "Statement",
										},
										&ruleRefExpr{
											pos:  position{line: 56, col: 37, offset: 898},
											name: "__",
										},
									},
								},
							},
						},
						&choiceExpr{
							pos: position{line: 56, col: 44, offset: 905},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 56, col: 44, offset: 905},
									name: "EOF",
								},
								&ruleRefExpr{
									pos:  position{line: 56, col: 50, offset: 911},
									name: "SyntaxError",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SyntaxError",
			pos:  position{line: 100, col: 1, offset: 2081},
			expr: &actionExpr{
				pos: position{line: 100, col: 15, offset: 2097},
				run: (*parser).callonSyntaxError1,
				expr: &anyMatcher{
					line: 100, col: 15, offset: 2097,
				},
			},
		},
		{
			name: "Include",
			pos:  position{line: 104, col: 1, offset: 2152},
			expr: &actionExpr{
				pos: position{line: 104, col: 11, offset: 2164},
				run: (*parser).callonInclude1,
				expr: &seqExpr{
					pos: position{line: 104, col: 11, offset: 2164},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 104, col: 11, offset: 2164},
							val:        "include",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 104, col: 21, offset: 2174},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 104, col: 23, offset: 2176},
							label: "file",
							expr: &ruleRefExpr{
								pos:  position{line: 104, col: 28, offset: 2181},
								name: "Literal",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 104, col: 36, offset: 2189},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Statement",
			pos:  position{line: 108, col: 1, offset: 2234},
			expr: &choiceExpr{
				pos: position{line: 108, col: 13, offset: 2248},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 108, col: 13, offset: 2248},
						name: "Include",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 23, offset: 2258},
						name: "Namespace",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 35, offset: 2270},
						name: "Const",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 43, offset: 2278},
						name: "Enum",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 50, offset: 2285},
						name: "TypeDef",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 60, offset: 2295},
						name: "Struct",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 69, offset: 2304},
						name: "Exception",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 81, offset: 2316},
						name: "Union",
					},
					&ruleRefExpr{
						pos:  position{line: 108, col: 89, offset: 2324},
						name: "Service",
					},
				},
			},
		},
		{
			name: "Namespace",
			pos:  position{line: 110, col: 1, offset: 2333},
			expr: &actionExpr{
				pos: position{line: 110, col: 13, offset: 2347},
				run: (*parser).callonNamespace1,
				expr: &seqExpr{
					pos: position{line: 110, col: 13, offset: 2347},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 110, col: 13, offset: 2347},
							val:        "namespace",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 110, col: 25, offset: 2359},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 110, col: 27, offset: 2361},
							label: "scope",
							expr: &oneOrMoreExpr{
								pos: position{line: 110, col: 33, offset: 2367},
								expr: &charClassMatcher{
									pos:        position{line: 110, col: 33, offset: 2367},
									val:        "[a-z.-]",
									chars:      []rune{'.', '-'},
									ranges:     []rune{'a', 'z'},
									ignoreCase: false,
									inverted:   false,
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 110, col: 42, offset: 2376},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 110, col: 44, offset: 2378},
							label: "ns",
							expr: &ruleRefExpr{
								pos:  position{line: 110, col: 47, offset: 2381},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 110, col: 58, offset: 2392},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Const",
			pos:  position{line: 117, col: 1, offset: 2503},
			expr: &actionExpr{
				pos: position{line: 117, col: 9, offset: 2513},
				run: (*parser).callonConst1,
				expr: &seqExpr{
					pos: position{line: 117, col: 9, offset: 2513},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 117, col: 9, offset: 2513},
							val:        "const",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 17, offset: 2521},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 117, col: 19, offset: 2523},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 23, offset: 2527},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 33, offset: 2537},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 117, col: 35, offset: 2539},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 40, offset: 2544},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 51, offset: 2555},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 117, col: 54, offset: 2558},
							val:        "=",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 58, offset: 2562},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 117, col: 61, offset: 2565},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 67, offset: 2571},
								name: "ConstValue",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 78, offset: 2582},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Enum",
			pos:  position{line: 125, col: 1, offset: 2690},
			expr: &actionExpr{
				pos: position{line: 125, col: 8, offset: 2699},
				run: (*parser).callonEnum1,
				expr: &seqExpr{
					pos: position{line: 125, col: 8, offset: 2699},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 125, col: 8, offset: 2699},
							val:        "enum",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 15, offset: 2706},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 125, col: 17, offset: 2708},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 22, offset: 2713},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 33, offset: 2724},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 125, col: 36, offset: 2727},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 40, offset: 2731},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 125, col: 43, offset: 2734},
							label: "values",
							expr: &zeroOrMoreExpr{
								pos: position{line: 125, col: 50, offset: 2741},
								expr: &seqExpr{
									pos: position{line: 125, col: 51, offset: 2742},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 125, col: 51, offset: 2742},
											name: "EnumValue",
										},
										&ruleRefExpr{
											pos:  position{line: 125, col: 61, offset: 2752},
											name: "__",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 125, col: 66, offset: 2757},
							val:        "}",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 70, offset: 2761},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "EnumValue",
			pos:  position{line: 148, col: 1, offset: 3277},
			expr: &actionExpr{
				pos: position{line: 148, col: 13, offset: 3291},
				run: (*parser).callonEnumValue1,
				expr: &seqExpr{
					pos: position{line: 148, col: 13, offset: 3291},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 148, col: 13, offset: 3291},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 148, col: 18, offset: 3296},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 148, col: 29, offset: 3307},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 148, col: 31, offset: 3309},
							label: "value",
							expr: &zeroOrOneExpr{
								pos: position{line: 148, col: 37, offset: 3315},
								expr: &seqExpr{
									pos: position{line: 148, col: 38, offset: 3316},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 148, col: 38, offset: 3316},
											val:        "=",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 148, col: 42, offset: 3320},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 148, col: 44, offset: 3322},
											name: "IntConstant",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 148, col: 58, offset: 3336},
							expr: &ruleRefExpr{
								pos:  position{line: 148, col: 58, offset: 3336},
								name: "TypeAnnotations",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 148, col: 75, offset: 3353},
							expr: &ruleRefExpr{
								pos:  position{line: 148, col: 75, offset: 3353},
								name: "ListSeparator",
							},
						},
					},
				},
			},
		},
		{
			name: "TypeDef",
			pos:  position{line: 159, col: 1, offset: 3532},
			expr: &actionExpr{
				pos: position{line: 159, col: 11, offset: 3544},
				run: (*parser).callonTypeDef1,
				expr: &seqExpr{
					pos: position{line: 159, col: 11, offset: 3544},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 159, col: 11, offset: 3544},
							val:        "typedef",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 159, col: 21, offset: 3554},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 159, col: 23, offset: 3556},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 27, offset: 3560},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 159, col: 37, offset: 3570},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 159, col: 39, offset: 3572},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 44, offset: 3577},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 159, col: 55, offset: 3588},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 159, col: 57, offset: 3590},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 159, col: 69, offset: 3602},
								expr: &ruleRefExpr{
									pos:  position{line: 159, col: 69, offset: 3602},
									name: "TypeAnnotations",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 159, col: 86, offset: 3619},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "Struct",
			pos:  position{line: 168, col: 1, offset: 3755},
			expr: &actionExpr{
				pos: position{line: 168, col: 10, offset: 3766},
				run: (*parser).callonStruct1,
				expr: &seqExpr{
					pos: position{line: 168, col: 10, offset: 3766},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 168, col: 10, offset: 3766},
							val:        "struct",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 168, col: 19, offset: 3775},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 168, col: 21, offset: 3777},
							label: "st",
							expr: &ruleRefExpr{
								pos:  position{line: 168, col: 24, offset: 3780},
								name: "StructLike",
							},
						},
					},
				},
			},
		},
		{
			name: "Exception",
			pos:  position{line: 169, col: 1, offset: 3820},
			expr: &actionExpr{
				pos: position{line: 169, col: 13, offset: 3834},
				run: (*parser).callonException1,
				expr: &seqExpr{
					pos: position{line: 169, col: 13, offset: 3834},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 169, col: 13, offset: 3834},
							val:        "exception",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 169, col: 25, offset: 3846},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 169, col: 27, offset: 3848},
							label: "st",
							expr: &ruleRefExpr{
								pos:  position{line: 169, col: 30, offset: 3851},
								name: "StructLike",
							},
						},
					},
				},
			},
		},
		{
			name: "Union",
			pos:  position{line: 170, col: 1, offset: 3902},
			expr: &actionExpr{
				pos: position{line: 170, col: 9, offset: 3912},
				run: (*parser).callonUnion1,
				expr: &seqExpr{
					pos: position{line: 170, col: 9, offset: 3912},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 170, col: 9, offset: 3912},
							val:        "union",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 170, col: 17, offset: 3920},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 170, col: 19, offset: 3922},
							label: "st",
							expr: &ruleRefExpr{
								pos:  position{line: 170, col: 22, offset: 3925},
								name: "StructLike",
							},
						},
					},
				},
			},
		},
		{
			name: "StructLike",
			pos:  position{line: 171, col: 1, offset: 3972},
			expr: &actionExpr{
				pos: position{line: 171, col: 14, offset: 3987},
				run: (*parser).callonStructLike1,
				expr: &seqExpr{
					pos: position{line: 171, col: 14, offset: 3987},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 171, col: 14, offset: 3987},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 171, col: 19, offset: 3992},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 30, offset: 4003},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 171, col: 33, offset: 4006},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 37, offset: 4010},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 171, col: 40, offset: 4013},
							label: "fields",
							expr: &ruleRefExpr{
								pos:  position{line: 171, col: 47, offset: 4020},
								name: "FieldList",
							},
						},
						&litMatcher{
							pos:        position{line: 171, col: 57, offset: 4030},
							val:        "}",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 171, col: 61, offset: 4034},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "FieldList",
			pos:  position{line: 181, col: 1, offset: 4168},
			expr: &actionExpr{
				pos: position{line: 181, col: 13, offset: 4182},
				run: (*parser).callonFieldList1,
				expr: &labeledExpr{
					pos:   position{line: 181, col: 13, offset: 4182},
					label: "fields",
					expr: &zeroOrMoreExpr{
						pos: position{line: 181, col: 20, offset: 4189},
						expr: &seqExpr{
							pos: position{line: 181, col: 21, offset: 4190},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 181, col: 21, offset: 4190},
									name: "Field",
								},
								&ruleRefExpr{
									pos:  position{line: 181, col: 27, offset: 4196},
									name: "__",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Field",
			pos:  position{line: 190, col: 1, offset: 4356},
			expr: &actionExpr{
				pos: position{line: 190, col: 9, offset: 4366},
				run: (*parser).callonField1,
				expr: &seqExpr{
					pos: position{line: 190, col: 9, offset: 4366},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 190, col: 9, offset: 4366},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 190, col: 12, offset: 4369},
								name: "IntConstant",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 190, col: 24, offset: 4381},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 190, col: 26, offset: 4383},
							val:        ":",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 190, col: 30, offset: 4387},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 190, col: 32, offset: 4389},
							label: "req",
							expr: &zeroOrOneExpr{
								pos: position{line: 190, col: 36, offset: 4393},
								expr: &ruleRefExpr{
									pos:  position{line: 190, col: 36, offset: 4393},
									name: "FieldReq",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 190, col: 46, offset: 4403},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 190, col: 48, offset: 4405},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 190, col: 52, offset: 4409},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 190, col: 62, offset: 4419},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 190, col: 64, offset: 4421},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 190, col: 69, offset: 4426},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 190, col: 80, offset: 4437},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 190, col: 83, offset: 4440},
							label: "def",
							expr: &zeroOrOneExpr{
								pos: position{line: 190, col: 87, offset: 4444},
								expr: &seqExpr{
									pos: position{line: 190, col: 88, offset: 4445},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 190, col: 88, offset: 4445},
											val:        "=",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 190, col: 92, offset: 4449},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 190, col: 94, offset: 4451},
											name: "ConstValue",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 190, col: 107, offset: 4464},
							expr: &ruleRefExpr{
								pos:  position{line: 190, col: 107, offset: 4464},
								name: "ListSeparator",
							},
						},
					},
				},
			},
		},
		{
			name: "FieldReq",
			pos:  position{line: 205, col: 1, offset: 4724},
			expr: &actionExpr{
				pos: position{line: 205, col: 12, offset: 4737},
				run: (*parser).callonFieldReq1,
				expr: &choiceExpr{
					pos: position{line: 205, col: 13, offset: 4738},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 205, col: 13, offset: 4738},
							val:        "required",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 205, col: 26, offset: 4751},
							val:        "optional",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Service",
			pos:  position{line: 209, col: 1, offset: 4822},
			expr: &actionExpr{
				pos: position{line: 209, col: 11, offset: 4834},
				run: (*parser).callonService1,
				expr: &seqExpr{
					pos: position{line: 209, col: 11, offset: 4834},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 209, col: 11, offset: 4834},
							val:        "service",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 209, col: 21, offset: 4844},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 209, col: 23, offset: 4846},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 209, col: 28, offset: 4851},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 209, col: 39, offset: 4862},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 209, col: 41, offset: 4864},
							label: "extends",
							expr: &zeroOrOneExpr{
								pos: position{line: 209, col: 49, offset: 4872},
								expr: &seqExpr{
									pos: position{line: 209, col: 50, offset: 4873},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 209, col: 50, offset: 4873},
											val:        "extends",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 209, col: 60, offset: 4883},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 209, col: 63, offset: 4886},
											name: "Identifier",
										},
										&ruleRefExpr{
											pos:  position{line: 209, col: 74, offset: 4897},
											name: "__",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 209, col: 79, offset: 4902},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 209, col: 82, offset: 4905},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 209, col: 86, offset: 4909},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 209, col: 89, offset: 4912},
							label: "methods",
							expr: &zeroOrMoreExpr{
								pos: position{line: 209, col: 97, offset: 4920},
								expr: &seqExpr{
									pos: position{line: 209, col: 98, offset: 4921},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 209, col: 98, offset: 4921},
											name: "Function",
										},
										&ruleRefExpr{
											pos:  position{line: 209, col: 107, offset: 4930},
											name: "__",
										},
									},
								},
							},
						},
						&choiceExpr{
							pos: position{line: 209, col: 113, offset: 4936},
							alternatives: []interface{}{
								&litMatcher{
									pos:        position{line: 209, col: 113, offset: 4936},
									val:        "}",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 209, col: 119, offset: 4942},
									name: "EndOfServiceError",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 209, col: 138, offset: 4961},
							name: "EOS",
						},
					},
				},
			},
		},
		{
			name: "EndOfServiceError",
			pos:  position{line: 224, col: 1, offset: 5302},
			expr: &actionExpr{
				pos: position{line: 224, col: 21, offset: 5324},
				run: (*parser).callonEndOfServiceError1,
				expr: &anyMatcher{
					line: 224, col: 21, offset: 5324,
				},
			},
		},
		{
			name: "Function",
			pos:  position{line: 228, col: 1, offset: 5390},
			expr: &actionExpr{
				pos: position{line: 228, col: 12, offset: 5403},
				run: (*parser).callonFunction1,
				expr: &seqExpr{
					pos: position{line: 228, col: 12, offset: 5403},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 228, col: 12, offset: 5403},
							label: "oneway",
							expr: &zeroOrOneExpr{
								pos: position{line: 228, col: 19, offset: 5410},
								expr: &seqExpr{
									pos: position{line: 228, col: 20, offset: 5411},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 228, col: 20, offset: 5411},
											val:        "oneway",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 228, col: 29, offset: 5420},
											name: "__",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 228, col: 34, offset: 5425},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 228, col: 38, offset: 5429},
								name: "FunctionType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 228, col: 51, offset: 5442},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 228, col: 54, offset: 5445},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 228, col: 59, offset: 5450},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 228, col: 70, offset: 5461},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 228, col: 72, offset: 5463},
							val:        "(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 228, col: 76, offset: 5467},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 228, col: 79, offset: 5470},
							label: "arguments",
							expr: &ruleRefExpr{
								pos:  position{line: 228, col: 89, offset: 5480},
								name: "FieldList",
							},
						},
						&litMatcher{
							pos:        position{line: 228, col: 99, offset: 5490},
							val:        ")",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 228, col: 103, offset: 5494},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 228, col: 106, offset: 5497},
							label: "exceptions",
							expr: &zeroOrOneExpr{
								pos: position{line: 228, col: 117, offset: 5508},
								expr: &ruleRefExpr{
									pos:  position{line: 228, col: 117, offset: 5508},
									name: "Throws",
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 228, col: 125, offset: 5516},
							expr: &ruleRefExpr{
								pos:  position{line: 228, col: 125, offset: 5516},
								name: "ListSeparator",
							},
						},
					},
				},
			},
		},
		{
			name: "FunctionType",
			pos:  position{line: 251, col: 1, offset: 5897},
			expr: &actionExpr{
				pos: position{line: 251, col: 16, offset: 5914},
				run: (*parser).callonFunctionType1,
				expr: &labeledExpr{
					pos:   position{line: 251, col: 16, offset: 5914},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 251, col: 21, offset: 5919},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 251, col: 21, offset: 5919},
								val:        "void",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 251, col: 30, offset: 5928},
								name: "FieldType",
							},
						},
					},
				},
			},
		},
		{
			name: "Throws",
			pos:  position{line: 258, col: 1, offset: 6035},
			expr: &actionExpr{
				pos: position{line: 258, col: 10, offset: 6046},
				run: (*parser).callonThrows1,
				expr: &seqExpr{
					pos: position{line: 258, col: 10, offset: 6046},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 258, col: 10, offset: 6046},
							val:        "throws",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 258, col: 19, offset: 6055},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 258, col: 22, offset: 6058},
							val:        "(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 258, col: 26, offset: 6062},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 258, col: 29, offset: 6065},
							label: "exceptions",
							expr: &ruleRefExpr{
								pos:  position{line: 258, col: 40, offset: 6076},
								name: "FieldList",
							},
						},
						&litMatcher{
							pos:        position{line: 258, col: 50, offset: 6086},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "FieldType",
			pos:  position{line: 262, col: 1, offset: 6119},
			expr: &actionExpr{
				pos: position{line: 262, col: 13, offset: 6133},
				run: (*parser).callonFieldType1,
				expr: &labeledExpr{
					pos:   position{line: 262, col: 13, offset: 6133},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 262, col: 18, offset: 6138},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 262, col: 18, offset: 6138},
								name: "BaseType",
							},
							&ruleRefExpr{
								pos:  position{line: 262, col: 29, offset: 6149},
								name: "ContainerType",
							},
							&ruleRefExpr{
								pos:  position{line: 262, col: 45, offset: 6165},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "DefinitionType",
			pos:  position{line: 269, col: 1, offset: 6275},
			expr: &actionExpr{
				pos: position{line: 269, col: 18, offset: 6294},
				run: (*parser).callonDefinitionType1,
				expr: &labeledExpr{
					pos:   position{line: 269, col: 18, offset: 6294},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 269, col: 23, offset: 6299},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 269, col: 23, offset: 6299},
								name: "BaseType",
							},
							&ruleRefExpr{
								pos:  position{line: 269, col: 34, offset: 6310},
								name: "ContainerType",
							},
						},
					},
				},
			},
		},
		{
			name: "BaseType",
			pos:  position{line: 273, col: 1, offset: 6347},
			expr: &actionExpr{
				pos: position{line: 273, col: 12, offset: 6360},
				run: (*parser).callonBaseType1,
				expr: &seqExpr{
					pos: position{line: 273, col: 12, offset: 6360},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 273, col: 12, offset: 6360},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 273, col: 17, offset: 6365},
								name: "BaseTypeName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 273, col: 30, offset: 6378},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 273, col: 33, offset: 6381},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 273, col: 45, offset: 6393},
								expr: &ruleRefExpr{
									pos:  position{line: 273, col: 45, offset: 6393},
									name: "TypeAnnotations",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BaseTypeName",
			pos:  position{line: 280, col: 1, offset: 6504},
			expr: &actionExpr{
				pos: position{line: 280, col: 16, offset: 6521},
				run: (*parser).callonBaseTypeName1,
				expr: &choiceExpr{
					pos: position{line: 280, col: 17, offset: 6522},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 280, col: 17, offset: 6522},
							val:        "bool",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 280, col: 26, offset: 6531},
							val:        "byte",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 280, col: 35, offset: 6540},
							val:        "i16",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 280, col: 43, offset: 6548},
							val:        "i32",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 280, col: 51, offset: 6556},
							val:        "i64",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 280, col: 59, offset: 6564},
							val:        "double",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 280, col: 70, offset: 6575},
							val:        "string",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 280, col: 81, offset: 6586},
							val:        "binary",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "ContainerType",
			pos:  position{line: 284, col: 1, offset: 6630},
			expr: &actionExpr{
				pos: position{line: 284, col: 17, offset: 6648},
				run: (*parser).callonContainerType1,
				expr: &labeledExpr{
					pos:   position{line: 284, col: 17, offset: 6648},
					label: "typ",
					expr: &choiceExpr{
						pos: position{line: 284, col: 22, offset: 6653},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 284, col: 22, offset: 6653},
								name: "MapType",
							},
							&ruleRefExpr{
								pos:  position{line: 284, col: 32, offset: 6663},
								name: "SetType",
							},
							&ruleRefExpr{
								pos:  position{line: 284, col: 42, offset: 6673},
								name: "ListType",
							},
						},
					},
				},
			},
		},
		{
			name: "MapType",
			pos:  position{line: 288, col: 1, offset: 6705},
			expr: &actionExpr{
				pos: position{line: 288, col: 11, offset: 6717},
				run: (*parser).callonMapType1,
				expr: &seqExpr{
					pos: position{line: 288, col: 11, offset: 6717},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 288, col: 11, offset: 6717},
							expr: &ruleRefExpr{
								pos:  position{line: 288, col: 11, offset: 6717},
								name: "CppType",
							},
						},
						&litMatcher{
							pos:        position{line: 288, col: 20, offset: 6726},
							val:        "map",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 288, col: 26, offset: 6732},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 288, col: 29, offset: 6735},
							val:        "<",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 288, col: 33, offset: 6739},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 288, col: 36, offset: 6742},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 288, col: 40, offset: 6746},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 288, col: 50, offset: 6756},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 288, col: 53, offset: 6759},
							val:        ",",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 288, col: 57, offset: 6763},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 288, col: 60, offset: 6766},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 288, col: 66, offset: 6772},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 288, col: 76, offset: 6782},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 288, col: 79, offset: 6785},
							val:        ">",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 288, col: 83, offset: 6789},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 288, col: 86, offset: 6792},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 288, col: 98, offset: 6804},
								expr: &ruleRefExpr{
									pos:  position{line: 288, col: 98, offset: 6804},
									name: "TypeAnnotations",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SetType",
			pos:  position{line: 297, col: 1, offset: 6959},
			expr: &actionExpr{
				pos: position{line: 297, col: 11, offset: 6971},
				run: (*parser).callonSetType1,
				expr: &seqExpr{
					pos: position{line: 297, col: 11, offset: 6971},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 297, col: 11, offset: 6971},
							expr: &ruleRefExpr{
								pos:  position{line: 297, col: 11, offset: 6971},
								name: "CppType",
							},
						},
						&litMatcher{
							pos:        position{line: 297, col: 20, offset: 6980},
							val:        "set",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 297, col: 26, offset: 6986},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 297, col: 29, offset: 6989},
							val:        "<",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 297, col: 33, offset: 6993},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 297, col: 36, offset: 6996},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 297, col: 40, offset: 7000},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 297, col: 50, offset: 7010},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 297, col: 53, offset: 7013},
							val:        ">",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 297, col: 57, offset: 7017},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 297, col: 60, offset: 7020},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 297, col: 72, offset: 7032},
								expr: &ruleRefExpr{
									pos:  position{line: 297, col: 72, offset: 7032},
									name: "TypeAnnotations",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ListType",
			pos:  position{line: 305, col: 1, offset: 7161},
			expr: &actionExpr{
				pos: position{line: 305, col: 12, offset: 7174},
				run: (*parser).callonListType1,
				expr: &seqExpr{
					pos: position{line: 305, col: 12, offset: 7174},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 305, col: 12, offset: 7174},
							val:        "list",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 305, col: 19, offset: 7181},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 305, col: 22, offset: 7184},
							val:        "<",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 305, col: 26, offset: 7188},
							name: "WS",
						},
						&labeledExpr{
							pos:   position{line: 305, col: 29, offset: 7191},
							label: "typ",
							expr: &ruleRefExpr{
								pos:  position{line: 305, col: 33, offset: 7195},
								name: "FieldType",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 305, col: 43, offset: 7205},
							name: "WS",
						},
						&litMatcher{
							pos:        position{line: 305, col: 46, offset: 7208},
							val:        ">",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 305, col: 50, offset: 7212},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 305, col: 53, offset: 7215},
							label: "annotations",
							expr: &zeroOrOneExpr{
								pos: position{line: 305, col: 65, offset: 7227},
								expr: &ruleRefExpr{
									pos:  position{line: 305, col: 65, offset: 7227},
									name: "TypeAnnotations",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CppType",
			pos:  position{line: 313, col: 1, offset: 7357},
			expr: &actionExpr{
				pos: position{line: 313, col: 11, offset: 7369},
				run: (*parser).callonCppType1,
				expr: &seqExpr{
					pos: position{line: 313, col: 11, offset: 7369},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 313, col: 11, offset: 7369},
							val:        "cpp_type",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 313, col: 22, offset: 7380},
							label: "cppType",
							expr: &ruleRefExpr{
								pos:  position{line: 313, col: 30, offset: 7388},
								name: "Literal",
							},
						},
					},
				},
			},
		},
		{
			name: "ConstValue",
			pos:  position{line: 317, col: 1, offset: 7422},
			expr: &choiceExpr{
				pos: position{line: 317, col: 14, offset: 7437},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 317, col: 14, offset: 7437},
						name: "Literal",
					},
					&ruleRefExpr{
						pos:  position{line: 317, col: 24, offset: 7447},
						name: "DoubleConstant",
					},
					&ruleRefExpr{
						pos:  position{line: 317, col: 41, offset: 7464},
						name: "IntConstant",
					},
					&ruleRefExpr{
						pos:  position{line: 317, col: 55, offset: 7478},
						name: "ConstMap",
					},
					&ruleRefExpr{
						pos:  position{line: 317, col: 66, offset: 7489},
						name: "ConstList",
					},
					&ruleRefExpr{
						pos:  position{line: 317, col: 78, offset: 7501},
						name: "Identifier",
					},
				},
			},
		},
		{
			name: "TypeAnnotations",
			pos:  position{line: 319, col: 1, offset: 7513},
			expr: &actionExpr{
				pos: position{line: 319, col: 19, offset: 7533},
				run: (*parser).callonTypeAnnotations1,
				expr: &seqExpr{
					pos: position{line: 319, col: 19, offset: 7533},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 319, col: 19, offset: 7533},
							val:        "(",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 319, col: 23, offset: 7537},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 319, col: 26, offset: 7540},
							label: "annotations",
							expr: &zeroOrMoreExpr{
								pos: position{line: 319, col: 38, offset: 7552},
								expr: &ruleRefExpr{
									pos:  position{line: 319, col: 38, offset: 7552},
									name: "TypeAnnotation",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 319, col: 54, offset: 7568},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "TypeAnnotation",
			pos:  position{line: 327, col: 1, offset: 7714},
			expr: &actionExpr{
				pos: position{line: 327, col: 18, offset: 7733},
				run: (*parser).callonTypeAnnotation1,
				expr: &seqExpr{
					pos: position{line: 327, col: 18, offset: 7733},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 327, col: 18, offset: 7733},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 327, col: 23, offset: 7738},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 327, col: 34, offset: 7749},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 327, col: 36, offset: 7751},
							label: "value",
							expr: &zeroOrOneExpr{
								pos: position{line: 327, col: 42, offset: 7757},
								expr: &actionExpr{
									pos: position{line: 327, col: 43, offset: 7758},
									run: (*parser).callonTypeAnnotation8,
									expr: &seqExpr{
										pos: position{line: 327, col: 43, offset: 7758},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 327, col: 43, offset: 7758},
												val:        "=",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 327, col: 47, offset: 7762},
												name: "__",
											},
											&labeledExpr{
												pos:   position{line: 327, col: 50, offset: 7765},
												label: "value",
												expr: &ruleRefExpr{
													pos:  position{line: 327, col: 56, offset: 7771},
													name: "Literal",
												},
											},
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 327, col: 88, offset: 7803},
							expr: &ruleRefExpr{
								pos:  position{line: 327, col: 88, offset: 7803},
								name: "ListSeparator",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 327, col: 103, offset: 7818},
							name: "__",
						},
					},
				},
			},
		},
		{
			name: "IntConstant",
			pos:  position{line: 338, col: 1, offset: 7981},
			expr: &actionExpr{
				pos: position{line: 338, col: 15, offset: 7997},
				run: (*parser).callonIntConstant1,
				expr: &seqExpr{
					pos: position{line: 338, col: 15, offset: 7997},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 338, col: 15, offset: 7997},
							expr: &charClassMatcher{
								pos:        position{line: 338, col: 15, offset: 7997},
								val:        "[-+]",
								chars:      []rune{'-', '+'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 338, col: 21, offset: 8003},
							expr: &ruleRefExpr{
								pos:  position{line: 338, col: 21, offset: 8003},
								name: "Digit",
							},
						},
					},
				},
			},
		},
		{
			name: "DoubleConstant",
			pos:  position{line: 342, col: 1, offset: 8064},
			expr: &actionExpr{
				pos: position{line: 342, col: 18, offset: 8083},
				run: (*parser).callonDoubleConstant1,
				expr: &seqExpr{
					pos: position{line: 342, col: 18, offset: 8083},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 342, col: 18, offset: 8083},
							expr: &charClassMatcher{
								pos:        position{line: 342, col: 18, offset: 8083},
								val:        "[+-]",
								chars:      []rune{'+', '-'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 342, col: 24, offset: 8089},
							expr: &ruleRefExpr{
								pos:  position{line: 342, col: 24, offset: 8089},
								name: "Digit",
							},
						},
						&litMatcher{
							pos:        position{line: 342, col: 31, offset: 8096},
							val:        ".",
							ignoreCase: false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 342, col: 35, offset: 8100},
							expr: &ruleRefExpr{
								pos:  position{line: 342, col: 35, offset: 8100},
								name: "Digit",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 342, col: 42, offset: 8107},
							expr: &seqExpr{
								pos: position{line: 342, col: 44, offset: 8109},
								exprs: []interface{}{
									&charClassMatcher{
										pos:        position{line: 342, col: 44, offset: 8109},
										val:        "['Ee']",
										chars:      []rune{'\'', 'E', 'e', '\''},
										ignoreCase: false,
										inverted:   false,
									},
									&ruleRefExpr{
										pos:  position{line: 342, col: 51, offset: 8116},
										name: "IntConstant",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ConstList",
			pos:  position{line: 346, col: 1, offset: 8183},
			expr: &actionExpr{
				pos: position{line: 346, col: 13, offset: 8197},
				run: (*parser).callonConstList1,
				expr: &seqExpr{
					pos: position{line: 346, col: 13, offset: 8197},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 346, col: 13, offset: 8197},
							val:        "[",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 346, col: 17, offset: 8201},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 346, col: 20, offset: 8204},
							label: "values",
							expr: &zeroOrMoreExpr{
								pos: position{line: 346, col: 27, offset: 8211},
								expr: &seqExpr{
									pos: position{line: 346, col: 28, offset: 8212},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 346, col: 28, offset: 8212},
											name: "ConstValue",
										},
										&ruleRefExpr{
											pos:  position{line: 346, col: 39, offset: 8223},
											name: "__",
										},
										&zeroOrOneExpr{
											pos: position{line: 346, col: 42, offset: 8226},
											expr: &ruleRefExpr{
												pos:  position{line: 346, col: 42, offset: 8226},
												name: "ListSeparator",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 346, col: 57, offset: 8241},
											name: "__",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 346, col: 62, offset: 8246},
							name: "__",
						},
						&litMatcher{
							pos:        position{line: 346, col: 65, offset: 8249},
							val:        "]",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "ConstMap",
			pos:  position{line: 355, col: 1, offset: 8422},
			expr: &actionExpr{
				pos: position{line: 355, col: 12, offset: 8435},
				run: (*parser).callonConstMap1,
				expr: &seqExpr{
					pos: position{line: 355, col: 12, offset: 8435},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 355, col: 12, offset: 8435},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 355, col: 16, offset: 8439},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 355, col: 19, offset: 8442},
							label: "values",
							expr: &zeroOrMoreExpr{
								pos: position{line: 355, col: 26, offset: 8449},
								expr: &seqExpr{
									pos: position{line: 355, col: 27, offset: 8450},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 355, col: 27, offset: 8450},
											name: "ConstValue",
										},
										&ruleRefExpr{
											pos:  position{line: 355, col: 38, offset: 8461},
											name: "__",
										},
										&litMatcher{
											pos:        position{line: 355, col: 41, offset: 8464},
											val:        ":",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 355, col: 45, offset: 8468},
											name: "__",
										},
										&ruleRefExpr{
											pos:  position{line: 355, col: 48, offset: 8471},
											name: "ConstValue",
										},
										&ruleRefExpr{
											pos:  position{line: 355, col: 59, offset: 8482},
											name: "__",
										},
										&choiceExpr{
											pos: position{line: 355, col: 63, offset: 8486},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 355, col: 63, offset: 8486},
													val:        ",",
													ignoreCase: false,
												},
												&andExpr{
													pos: position{line: 355, col: 69, offset: 8492},
													expr: &litMatcher{
														pos:        position{line: 355, col: 70, offset: 8493},
														val:        "}",
														ignoreCase: false,
													},
												},
											},
										},
										&ruleRefExpr{
											pos:  position{line: 355, col: 75, offset: 8498},
											name: "__",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 355, col: 80, offset: 8503},
							val:        "}",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Literal",
			pos:  position{line: 371, col: 1, offset: 8749},
			expr: &actionExpr{
				pos: position{line: 371, col: 11, offset: 8761},
				run: (*parser).callonLiteral1,
				expr: &choiceExpr{
					pos: position{line: 371, col: 12, offset: 8762},
					alternatives: []interface{}{
						&seqExpr{
							pos: position{line: 371, col: 13, offset: 8763},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 371, col: 13, offset: 8763},
									val:        "\"",
									ignoreCase: false,
								},
								&zeroOrMoreExpr{
									pos: position{line: 371, col: 17, offset: 8767},
									expr: &choiceExpr{
										pos: position{line: 371, col: 18, offset: 8768},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 371, col: 18, offset: 8768},
												val:        "\\\"",
												ignoreCase: false,
											},
											&charClassMatcher{
												pos:        position{line: 371, col: 25, offset: 8775},
												val:        "[^\"]",
												chars:      []rune{'"'},
												ignoreCase: false,
												inverted:   true,
											},
										},
									},
								},
								&litMatcher{
									pos:        position{line: 371, col: 32, offset: 8782},
									val:        "\"",
									ignoreCase: false,
								},
							},
						},
						&seqExpr{
							pos: position{line: 371, col: 40, offset: 8790},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 371, col: 40, offset: 8790},
									val:        "'",
									ignoreCase: false,
								},
								&zeroOrMoreExpr{
									pos: position{line: 371, col: 45, offset: 8795},
									expr: &choiceExpr{
										pos: position{line: 371, col: 46, offset: 8796},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 371, col: 46, offset: 8796},
												val:        "\\'",
												ignoreCase: false,
											},
											&charClassMatcher{
												pos:        position{line: 371, col: 53, offset: 8803},
												val:        "[^']",
												chars:      []rune{'\''},
												ignoreCase: false,
												inverted:   true,
											},
										},
									},
								},
								&litMatcher{
									pos:        position{line: 371, col: 60, offset: 8810},
									val:        "'",
									ignoreCase: false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 378, col: 1, offset: 9011},
			expr: &actionExpr{
				pos: position{line: 378, col: 14, offset: 9026},
				run: (*parser).callonIdentifier1,
				expr: &seqExpr{
					pos: position{line: 378, col: 14, offset: 9026},
					exprs: []interface{}{
						&oneOrMoreExpr{
							pos: position{line: 378, col: 14, offset: 9026},
							expr: &choiceExpr{
								pos: position{line: 378, col: 15, offset: 9027},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 378, col: 15, offset: 9027},
										name: "Letter",
									},
									&litMatcher{
										pos:        position{line: 378, col: 24, offset: 9036},
										val:        "_",
										ignoreCase: false,
									},
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 378, col: 30, offset: 9042},
							expr: &choiceExpr{
								pos: position{line: 378, col: 31, offset: 9043},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 378, col: 31, offset: 9043},
										name: "Letter",
									},
									&ruleRefExpr{
										pos:  position{line: 378, col: 40, offset: 9052},
										name: "Digit",
									},
									&charClassMatcher{
										pos:        position{line: 378, col: 48, offset: 9060},
										val:        "[._]",
										chars:      []rune{'.', '_'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ListSeparator",
			pos:  position{line: 382, col: 1, offset: 9112},
			expr: &charClassMatcher{
				pos:        position{line: 382, col: 17, offset: 9130},
				val:        "[,;]",
				chars:      []rune{',', ';'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Letter",
			pos:  position{line: 383, col: 1, offset: 9135},
			expr: &charClassMatcher{
				pos:        position{line: 383, col: 10, offset: 9146},
				val:        "[A-Za-z]",
				ranges:     []rune{'A', 'Z', 'a', 'z'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Digit",
			pos:  position{line: 384, col: 1, offset: 9155},
			expr: &charClassMatcher{
				pos:        position{line: 384, col: 9, offset: 9165},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "SourceChar",
			pos:  position{line: 388, col: 1, offset: 9176},
			expr: &anyMatcher{
				line: 388, col: 14, offset: 9191,
			},
		},
		{
			name: "Comment",
			pos:  position{line: 389, col: 1, offset: 9193},
			expr: &choiceExpr{
				pos: position{line: 389, col: 11, offset: 9205},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 389, col: 11, offset: 9205},
						name: "MultiLineComment",
					},
					&ruleRefExpr{
						pos:  position{line: 389, col: 30, offset: 9224},
						name: "SingleLineComment",
					},
				},
			},
		},
		{
			name: "MultiLineComment",
			pos:  position{line: 390, col: 1, offset: 9242},
			expr: &seqExpr{
				pos: position{line: 390, col: 20, offset: 9263},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 390, col: 20, offset: 9263},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 390, col: 25, offset: 9268},
						expr: &seqExpr{
							pos: position{line: 390, col: 27, offset: 9270},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 390, col: 27, offset: 9270},
									expr: &litMatcher{
										pos:        position{line: 390, col: 28, offset: 9271},
										val:        "*/",
										ignoreCase: false,
									},
								},
								&ruleRefExpr{
									pos:  position{line: 390, col: 33, offset: 9276},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 390, col: 47, offset: 9290},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "MultiLineCommentNoLineTerminator",
			pos:  position{line: 391, col: 1, offset: 9295},
			expr: &seqExpr{
				pos: position{line: 391, col: 36, offset: 9332},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 391, col: 36, offset: 9332},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 391, col: 41, offset: 9337},
						expr: &seqExpr{
							pos: position{line: 391, col: 43, offset: 9339},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 391, col: 43, offset: 9339},
									expr: &choiceExpr{
										pos: position{line: 391, col: 46, offset: 9342},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 391, col: 46, offset: 9342},
												val:        "*/",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 391, col: 53, offset: 9349},
												name: "EOL",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 391, col: 59, offset: 9355},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 391, col: 73, offset: 9369},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 392, col: 1, offset: 9374},
			expr: &choiceExpr{
				pos: position{line: 392, col: 21, offset: 9396},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 392, col: 22, offset: 9397},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 392, col: 22, offset: 9397},
								val:        "//",
								ignoreCase: false,
							},
							&zeroOrMoreExpr{
								pos: position{line: 392, col: 27, offset: 9402},
								expr: &seqExpr{
									pos: position{line: 392, col: 29, offset: 9404},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 392, col: 29, offset: 9404},
											expr: &ruleRefExpr{
												pos:  position{line: 392, col: 30, offset: 9405},
												name: "EOL",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 392, col: 34, offset: 9409},
											name: "SourceChar",
										},
									},
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 392, col: 52, offset: 9427},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 392, col: 52, offset: 9427},
								val:        "#",
								ignoreCase: false,
							},
							&zeroOrMoreExpr{
								pos: position{line: 392, col: 56, offset: 9431},
								expr: &seqExpr{
									pos: position{line: 392, col: 58, offset: 9433},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 392, col: 58, offset: 9433},
											expr: &ruleRefExpr{
												pos:  position{line: 392, col: 59, offset: 9434},
												name: "EOL",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 392, col: 63, offset: 9438},
											name: "SourceChar",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 394, col: 1, offset: 9454},
			expr: &zeroOrMoreExpr{
				pos: position{line: 394, col: 6, offset: 9461},
				expr: &choiceExpr{
					pos: position{line: 394, col: 8, offset: 9463},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 394, col: 8, offset: 9463},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 394, col: 21, offset: 9476},
							name: "EOL",
						},
						&ruleRefExpr{
							pos:  position{line: 394, col: 27, offset: 9482},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 395, col: 1, offset: 9493},
			expr: &zeroOrMoreExpr{
				pos: position{line: 395, col: 5, offset: 9499},
				expr: &choiceExpr{
					pos: position{line: 395, col: 7, offset: 9501},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 395, col: 7, offset: 9501},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 395, col: 20, offset: 9514},
							name: "MultiLineCommentNoLineTerminator",
						},
					},
				},
			},
		},
		{
			name: "WS",
			pos:  position{line: 396, col: 1, offset: 9550},
			expr: &zeroOrMoreExpr{
				pos: position{line: 396, col: 6, offset: 9557},
				expr: &ruleRefExpr{
					pos:  position{line: 396, col: 6, offset: 9557},
					name: "Whitespace",
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 398, col: 1, offset: 9570},
			expr: &charClassMatcher{
				pos:        position{line: 398, col: 14, offset: 9585},
				val:        "[ \\t\\r]",
				chars:      []rune{' ', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOL",
			pos:  position{line: 399, col: 1, offset: 9593},
			expr: &litMatcher{
				pos:        position{line: 399, col: 7, offset: 9601},
				val:        "\n",
				ignoreCase: false,
			},
		},
		{
			name: "EOS",
			pos:  position{line: 400, col: 1, offset: 9606},
			expr: &choiceExpr{
				pos: position{line: 400, col: 7, offset: 9614},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 400, col: 7, offset: 9614},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 400, col: 7, offset: 9614},
								name: "__",
							},
							&litMatcher{
								pos:        position{line: 400, col: 10, offset: 9617},
								val:        ";",
								ignoreCase: false,
							},
						},
					},
					&seqExpr{
						pos: position{line: 400, col: 16, offset: 9623},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 400, col: 16, offset: 9623},
								name: "_",
							},
							&zeroOrOneExpr{
								pos: position{line: 400, col: 18, offset: 9625},
								expr: &ruleRefExpr{
									pos:  position{line: 400, col: 18, offset: 9625},
									name: "SingleLineComment",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 400, col: 37, offset: 9644},
								name: "EOL",
							},
						},
					},
					&seqExpr{
						pos: position{line: 400, col: 43, offset: 9650},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 400, col: 43, offset: 9650},
								name: "__",
							},
							&ruleRefExpr{
								pos:  position{line: 400, col: 46, offset: 9653},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 402, col: 1, offset: 9658},
			expr: &notExpr{
				pos: position{line: 402, col: 7, offset: 9666},
				expr: &anyMatcher{
					line: 402, col: 8, offset: 9667,
				},
			},
		},
	},
}

func (c *current) onGrammar1(statements interface{}) (interface{}, error) {
	thrift := &Thrift{
		Includes:   make(map[string]string),
		Namespaces: make(map[string]string),
		Typedefs:   make(map[string]*Typedef),
		Constants:  make(map[string]*Constant),
		Enums:      make(map[string]*Enum),
		Structs:    make(map[string]*Struct),
		Exceptions: make(map[string]*Struct),
		Unions:     make(map[string]*Struct),
		Services:   make(map[string]*Service),
	}
	stmts := toIfaceSlice(statements)
	for _, st := range stmts {
		switch v := st.([]interface{})[0].(type) {
		case *namespace:
			thrift.Namespaces[v.scope] = v.namespace
		case *Constant:
			thrift.Constants[v.Name] = v
		case *Enum:
			thrift.Enums[v.Name] = v
		case *Typedef:
			thrift.Typedefs[v.Alias] = v
		case *Struct:
			thrift.Structs[v.Name] = v
		case exception:
			thrift.Exceptions[v.Name] = (*Struct)(v)
		case union:
			thrift.Unions[v.Name] = unionToStruct(v)
		case *Service:
			thrift.Services[v.Name] = v
		case include:
			name := filepath.Base(string(v))
			if ix := strings.LastIndex(name, "."); ix > 0 {
				name = name[:ix]
			}
			thrift.Includes[name] = string(v)
		default:
			return nil, fmt.Errorf("parser: unknown value %#v", v)
		}
	}
	return thrift, nil
}

func (p *parser) callonGrammar1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGrammar1(stack["statements"])
}

func (c *current) onSyntaxError1() (interface{}, error) {
	return nil, errors.New("parser: syntax error")
}

func (p *parser) callonSyntaxError1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSyntaxError1()
}

func (c *current) onInclude1(file interface{}) (interface{}, error) {
	return include(file.(string)), nil
}

func (p *parser) callonInclude1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInclude1(stack["file"])
}

func (c *current) onNamespace1(scope, ns interface{}) (interface{}, error) {
	return &namespace{
		scope:     ifaceSliceToString(scope),
		namespace: string(ns.(Identifier)),
	}, nil
}

func (p *parser) callonNamespace1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNamespace1(stack["scope"], stack["ns"])
}

func (c *current) onConst1(typ, name, value interface{}) (interface{}, error) {
	return &Constant{
		Name:  string(name.(Identifier)),
		Type:  typ.(*Type),
		Value: value,
	}, nil
}

func (p *parser) callonConst1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConst1(stack["typ"], stack["name"], stack["value"])
}

func (c *current) onEnum1(name, values interface{}) (interface{}, error) {
	vs := toIfaceSlice(values)
	en := &Enum{
		Name:   string(name.(Identifier)),
		Values: make(map[string]*EnumValue, len(vs)),
	}
	// Assigns numbers in order. This will behave badly if some values are
	// defined and other are not, but I think that's ok since that's a silly
	// thing to do.
	next := 0
	for _, v := range vs {
		ev := v.([]interface{})[0].(*EnumValue)
		if ev.Value < 0 {
			ev.Value = next
		}
		if ev.Value >= next {
			next = ev.Value + 1
		}
		en.Values[ev.Name] = ev
	}
	return en, nil
}

func (p *parser) callonEnum1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEnum1(stack["name"], stack["values"])
}

func (c *current) onEnumValue1(name, value interface{}) (interface{}, error) {
	ev := &EnumValue{
		Name:  string(name.(Identifier)),
		Value: -1,
	}
	if value != nil {
		ev.Value = int(value.([]interface{})[2].(int64))
	}
	return ev, nil
}

func (p *parser) callonEnumValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEnumValue1(stack["name"], stack["value"])
}

func (c *current) onTypeDef1(typ, name, annotations interface{}) (interface{}, error) {
	return &Typedef{
		Type: typ.(*Type),

		Alias:       string(name.(Identifier)),
		Annotations: toAnnotations(annotations),
	}, nil
}

func (p *parser) callonTypeDef1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeDef1(stack["typ"], stack["name"], stack["annotations"])
}

func (c *current) onStruct1(st interface{}) (interface{}, error) {
	return st.(*Struct), nil
}

func (p *parser) callonStruct1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStruct1(stack["st"])
}

func (c *current) onException1(st interface{}) (interface{}, error) {
	return exception(st.(*Struct)), nil
}

func (p *parser) callonException1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onException1(stack["st"])
}

func (c *current) onUnion1(st interface{}) (interface{}, error) {
	return union(st.(*Struct)), nil
}

func (p *parser) callonUnion1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnion1(stack["st"])
}

func (c *current) onStructLike1(name, fields interface{}) (interface{}, error) {
	st := &Struct{
		Name: string(name.(Identifier)),
	}
	if fields != nil {
		st.Fields = fields.([]*Field)
	}
	return st, nil
}

func (p *parser) callonStructLike1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStructLike1(stack["name"], stack["fields"])
}

func (c *current) onFieldList1(fields interface{}) (interface{}, error) {
	fs := fields.([]interface{})
	flds := make([]*Field, len(fs))
	for i, f := range fs {
		flds[i] = f.([]interface{})[0].(*Field)
	}
	return flds, nil
}

func (p *parser) callonFieldList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldList1(stack["fields"])
}

func (c *current) onField1(id, req, typ, name, def interface{}) (interface{}, error) {
	f := &Field{
		ID:   int(id.(int64)),
		Name: string(name.(Identifier)),
		Type: typ.(*Type),
	}
	if req != nil && !req.(bool) {
		f.Optional = true
	}
	if def != nil {
		f.Default = def.([]interface{})[2]
	}
	return f, nil
}

func (p *parser) callonField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["id"], stack["req"], stack["typ"], stack["name"], stack["def"])
}

func (c *current) onFieldReq1() (interface{}, error) {
	return !bytes.Equal(c.text, []byte("optional")), nil
}

func (p *parser) callonFieldReq1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldReq1()
}

func (c *current) onService1(name, extends, methods interface{}) (interface{}, error) {
	ms := methods.([]interface{})
	svc := &Service{
		Name:    string(name.(Identifier)),
		Methods: make(map[string]*Method, len(ms)),
	}
	if extends != nil {
		svc.Extends = string(extends.([]interface{})[2].(Identifier))
	}
	for _, m := range ms {
		mt := m.([]interface{})[0].(*Method)
		svc.Methods[mt.Name] = mt
	}
	return svc, nil
}

func (p *parser) callonService1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onService1(stack["name"], stack["extends"], stack["methods"])
}

func (c *current) onEndOfServiceError1() (interface{}, error) {
	return nil, errors.New("parser: expected end of service")
}

func (p *parser) callonEndOfServiceError1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEndOfServiceError1()
}

func (c *current) onFunction1(oneway, typ, name, arguments, exceptions interface{}) (interface{}, error) {
	m := &Method{
		Name: string(name.(Identifier)),
	}
	t := typ.(*Type)
	if t.Name != "void" {
		m.ReturnType = t
	}
	if oneway != nil {
		m.Oneway = true
	}
	if arguments != nil {
		m.Arguments = arguments.([]*Field)
	}
	if exceptions != nil {
		m.Exceptions = exceptions.([]*Field)
		for _, e := range m.Exceptions {
			e.Optional = true
		}
	}
	return m, nil
}

func (p *parser) callonFunction1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunction1(stack["oneway"], stack["typ"], stack["name"], stack["arguments"], stack["exceptions"])
}

func (c *current) onFunctionType1(typ interface{}) (interface{}, error) {
	if t, ok := typ.(*Type); ok {
		return t, nil
	}
	return &Type{Name: string(c.text)}, nil
}

func (p *parser) callonFunctionType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionType1(stack["typ"])
}

func (c *current) onThrows1(exceptions interface{}) (interface{}, error) {
	return exceptions, nil
}

func (p *parser) callonThrows1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onThrows1(stack["exceptions"])
}

func (c *current) onFieldType1(typ interface{}) (interface{}, error) {
	if t, ok := typ.(Identifier); ok {
		return &Type{Name: string(t)}, nil
	}
	return typ, nil
}

func (p *parser) callonFieldType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldType1(stack["typ"])
}

func (c *current) onDefinitionType1(typ interface{}) (interface{}, error) {
	return typ, nil
}

func (p *parser) callonDefinitionType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefinitionType1(stack["typ"])
}

func (c *current) onBaseType1(name, annotations interface{}) (interface{}, error) {
	return &Type{
		Name:        name.(string),
		Annotations: toAnnotations(annotations),
	}, nil
}

func (p *parser) callonBaseType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBaseType1(stack["name"], stack["annotations"])
}

func (c *current) onBaseTypeName1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonBaseTypeName1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBaseTypeName1()
}

func (c *current) onContainerType1(typ interface{}) (interface{}, error) {
	return typ, nil
}

func (p *parser) callonContainerType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onContainerType1(stack["typ"])
}

func (c *current) onMapType1(key, value, annotations interface{}) (interface{}, error) {
	return &Type{
		Name:        "map",
		KeyType:     key.(*Type),
		ValueType:   value.(*Type),
		Annotations: toAnnotations(annotations),
	}, nil
}

func (p *parser) callonMapType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMapType1(stack["key"], stack["value"], stack["annotations"])
}

func (c *current) onSetType1(typ, annotations interface{}) (interface{}, error) {
	return &Type{
		Name:        "set",
		ValueType:   typ.(*Type),
		Annotations: toAnnotations(annotations),
	}, nil
}

func (p *parser) callonSetType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSetType1(stack["typ"], stack["annotations"])
}

func (c *current) onListType1(typ, annotations interface{}) (interface{}, error) {
	return &Type{
		Name:        "list",
		ValueType:   typ.(*Type),
		Annotations: toAnnotations(annotations),
	}, nil
}

func (p *parser) callonListType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onListType1(stack["typ"], stack["annotations"])
}

func (c *current) onCppType1(cppType interface{}) (interface{}, error) {
	return cppType, nil
}

func (p *parser) callonCppType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCppType1(stack["cppType"])
}

func (c *current) onTypeAnnotations1(annotations interface{}) (interface{}, error) {
	var anns []*Annotation
	for _, ann := range annotations.([]interface{}) {
		anns = append(anns, ann.(*Annotation))
	}
	return anns, nil
}

func (p *parser) callonTypeAnnotations1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAnnotations1(stack["annotations"])
}

func (c *current) onTypeAnnotation8(value interface{}) (interface{}, error) {
	return value, nil
}

func (p *parser) callonTypeAnnotation8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAnnotation8(stack["value"])
}

func (c *current) onTypeAnnotation1(name, value interface{}) (interface{}, error) {
	var optValue string
	if value != nil {
		optValue = value.(string)
	}
	return &Annotation{
		Name:  string(name.(Identifier)),
		Value: optValue,
	}, nil
}

func (p *parser) callonTypeAnnotation1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAnnotation1(stack["name"], stack["value"])
}

func (c *current) onIntConstant1() (interface{}, error) {
	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonIntConstant1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIntConstant1()
}

func (c *current) onDoubleConstant1() (interface{}, error) {
	return strconv.ParseFloat(string(c.text), 64)
}

func (p *parser) callonDoubleConstant1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoubleConstant1()
}

func (c *current) onConstList1(values interface{}) (interface{}, error) {
	valueSlice := values.([]interface{})
	vs := make([]interface{}, len(valueSlice))
	for i, v := range valueSlice {
		vs[i] = v.([]interface{})[0]
	}
	return vs, nil
}

func (p *parser) callonConstList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstList1(stack["values"])
}

func (c *current) onConstMap1(values interface{}) (interface{}, error) {
	if values == nil {
		return nil, nil
	}
	vals := values.([]interface{})
	kvs := make([]KeyValue, len(vals))
	for i, kv := range vals {
		v := kv.([]interface{})
		kvs[i] = KeyValue{
			Key:   v[0],
			Value: v[4],
		}
	}
	return kvs, nil
}

func (p *parser) callonConstMap1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstMap1(stack["values"])
}

func (c *current) onLiteral1() (interface{}, error) {
	if len(c.text) != 0 && c.text[0] == '\'' {
		return strconv.Unquote(`"` + strings.Replace(string(c.text[1:len(c.text)-1]), `\'`, `'`, -1) + `"`)
	}
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonLiteral1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLiteral1()
}

func (c *current) onIdentifier1() (interface{}, error) {
	return Identifier(string(c.text)), nil
}

func (p *parser) callonIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errNoMatch is returned if no match could be found.
	errNoMatch = errors.New("no match found")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (interface{}, error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match
}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos        position
	val        string
	chars      []rune
	ranges     []rune
	classes    []*unicode.RangeTable
	ignoreCase bool
	inverted   bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner  error
	pos    position
	prefix string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
	}
	p.setOptions(opts)
	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	recover bool
	debug   bool
	depth   int

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// stats
	exprCnt int
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position)
}

func (p *parser) addErrAt(err error, pos position) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, prefix: buf.String()}
	p.errs.add(pe)
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError {
		if n > 0 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	// start rule is rule [0]
	p.read() // advance to first rune
	val, ok := p.parseRule(g.rules[0])
	if !ok {
		if len(*p.errs) == 0 {
			// make sure this doesn't go out silently
			p.addErr(errNoMatch)
		}
		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint
	var ok bool

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.exprCnt++
	var val interface{}
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position)
		}
		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restore(pt)
	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn != utf8.RuneError {
		start := p.pt
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	// can't match EOF
	if cur == utf8.RuneError {
		return nil, false
	}
	start := p.pt
	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for _, alt := range ch.alternatives {
		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(not.expr)
	p.popV()
	p.restore(pt)
	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	var vals []interface{}

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
