// This file is automatically generated. Do not modify.

package gentest

import (
	"fmt"
)

var _ = fmt.Sprintf

type ByteAndListByte struct {
	AByte     int8   `thrift:"1,required,implicit" json:"a_byte"`
	AListByte []int8 `thrift:"2,required,implicit" json:"a_list_byte"`
}
